export type AnalyticsLanguage = "de" | "en" | "zh";
export const analyticsCopy = {
  en: {
    "analytics.providerProcessing": "Cloudflare’s browser check processes connection and browser signals, including IP address, TLS fingerprint and user agent, to detect bots and improve detection. Its privacy policy applies.",
    "analytics.retention": "Temporary request codes expire within two minutes and are normally removed from the application within three minutes. Service-provider recovery backups may retain them for up to seven days. This processing is not fully anonymous.",
    "analytics.providerPolicy": "Cloudflare privacy notice",

    "analytics.title": "Map visits",
    "analytics.notConnected": "Visit statistics are not connected yet.",
    "analytics.unavailable": "Visit statistics are currently unavailable.",
    "analytics.loading": "Loading visit statistics…",
    "analytics.pv": "Counted page views: {count}",
    "analytics.small": "Too few page views to publish a total.",
    "analytics.countries": "Page views by country or region",
    "analytics.other": "Other or unknown",
    "analytics.generated": "Statistics updated: {time}",
    "analytics.note": "Only page views you choose to share are counted; individual visitors are not counted. Groups below 20 views are hidden or combined. Totals are rounded down to the nearest 10, so displayed groups may not add up to the total. Checks limit abuse, but the figures can still be manipulated.",
    "analytics.privacy": "Counting is optional. Cloudflare estimates the country from the connection. CrimeMaps keeps country totals and temporary records used to limit repeated requests; these use a code derived from the connection address. CrimeMaps does not save your IP address. The browser check contacts Cloudflare, which processes connection data under its own terms.",
    "analytics.enable": "Count this page view",
    "analytics.verifying": "Checking this page view…",
    "analytics.accepted": "This page view was counted.",
    "analytics.notCounted": "This page view was not counted.",
    "analytics.preference": "Your browser’s privacy setting prevents this page view from being counted.",
  },
  de: {
    "analytics.providerProcessing": "Die Browserprüfung von Cloudflare verarbeitet Verbindungs- und Browsersignale, darunter IP-Adresse, TLS-Fingerabdruck und Browserkennung, um Bots zu erkennen und die Erkennung zu verbessern. Es gilt die Datenschutzerklärung des Dienstes.",
    "analytics.retention": "Temporäre Anfragecodes verfallen nach spätestens zwei Minuten und werden normalerweise innerhalb von drei Minuten aus der Anwendung entfernt. Wiederherstellungsdaten des Anbieters können sie bis zu sieben Tage enthalten. Diese Verarbeitung ist nicht vollständig anonym.",
    "analytics.providerPolicy": "Datenschutzhinweis von Cloudflare",

    "analytics.title": "Kartenbesuche",
    "analytics.notConnected": "Die Besucherstatistik ist noch nicht angeschlossen.",
    "analytics.unavailable": "Die Besucherstatistik ist derzeit nicht verfügbar.",
    "analytics.loading": "Besucherstatistik wird geladen…",
    "analytics.pv": "Gezählte Seitenaufrufe: {count}",
    "analytics.small": "Zu wenige Seitenaufrufe, um eine Summe zu veröffentlichen.",
    "analytics.countries": "Seitenaufrufe nach Ländern und Regionen",
    "analytics.other": "Sonstige oder unbekannt",
    "analytics.generated": "Statistik aktualisiert: {time}",
    "analytics.note": "Gezählt werden nur Seitenaufrufe, deren Übertragung Sie erlauben, keine einzelnen Besucher. Gruppen mit weniger als 20 Aufrufen werden ausgeblendet oder zusammengefasst. Die Zahlen werden auf volle Zehner abgerundet; deshalb können die angezeigten Gruppen von der Gesamtsumme abweichen. Prüfungen begrenzen Missbrauch, verhindern aber nicht jede Manipulation.",
    "analytics.privacy": "Die Zählung ist freiwillig. Cloudflare schätzt das Land anhand der Verbindung. CrimeMaps speichert Ländersummen und kurzzeitig Einträge mit einem aus der Verbindungsadresse abgeleiteten Code, um wiederholte Anfragen zu begrenzen. Ihre IP-Adresse wird in CrimeMaps nicht gespeichert. Die Browserprüfung kontaktiert Cloudflare; der Anbieter verarbeitet Verbindungsdaten nach seinen eigenen Bedingungen. Vollständige Anonymität kann damit nicht zugesagt werden.",
    "analytics.enable": "Diesen Seitenaufruf zählen",
    "analytics.verifying": "Seitenaufruf wird geprüft…",
    "analytics.accepted": "Dieser Seitenaufruf wurde gezählt.",
    "analytics.notCounted": "Dieser Seitenaufruf wurde nicht gezählt.",
    "analytics.preference": "Die Datenschutzeinstellung Ihres Browsers verhindert die Zählung dieses Seitenaufrufs.",
  },
  zh: {
    "analytics.providerProcessing": "Cloudflare的浏览器检查会处理IP地址、TLS指纹和浏览器标识等连接及浏览器信息，用于识别机器人和改进识别能力，适用该服务的隐私条款。",
    "analytics.retention": "临时请求编号在两分钟内失效，通常会在三分钟内从应用删除；服务商的恢复备份可能保留最多七天。这种处理并非完全匿名。",
    "analytics.providerPolicy": "Cloudflare隐私说明",

    "analytics.title": "地图访问",
    "analytics.notConnected": "访问统计尚未接入。",
    "analytics.unavailable": "访问统计暂时不可用。",
    "analytics.loading": "正在读取访问统计…",
    "analytics.pv": "已计入的页面浏览次数：{count}",
    "analytics.small": "浏览次数较少，暂不公布总数。",
    "analytics.countries": "页面访问国家／地区分布",
    "analytics.other": "其他／未知",
    "analytics.generated": "统计更新时间：{time}",
    "analytics.note": "仅统计主动启用的页面浏览，不统计独立访客。少于20次的分组会合并或隐藏，数字按10次向下取整，各项相加可能与总数不同。系统会检查并限制重复请求，但数字仍可能被人为增加。",
    "analytics.privacy": "是否计入本次页面浏览？Cloudflare会根据连接信息估计国家。CrimeMaps保存国家累计数，并短期保存根据连接地址生成的临时编号，以限制重复请求；不保存原始IP地址。浏览器检查会联系Cloudflare，该服务按自身条款处理连接信息；这种处理不能保证完全匿名。",
    "analytics.enable": "计入本次页面浏览",
    "analytics.verifying": "正在检查本次浏览…",
    "analytics.accepted": "本次页面浏览已计入。",
    "analytics.notCounted": "本次页面浏览未计入。",
    "analytics.preference": "浏览器的隐私设置已阻止本次浏览计数。",
  },
} as const;
export type AnalyticsKey = keyof typeof analyticsCopy.en;
