import {officialMunicipalScopes,datedMetricValue,type AreaMetric} from './area-metrics';
import {referenceObservation,type SourceRule} from './reference-registry-matcher';
import {appendMetricVisual} from './metric-visualization';
import type {Observation,Text} from './reference-fallback';
export const BREMEN2023_REFS={metric:{path:'/safety/geography/reference-optional/bremen-02077deedf1679bf28fdd4b0f1783bb9eb9e558e971eaee90599c4bad3401be5.json',sha256:'02077deedf1679bf28fdd4b0f1783bb9eb9e558e971eaee90599c4bad3401be5',bytes:5862},rules:{path:'/safety/geography/reference-optional/bremen-51ec9482a97ae37bc3b157494f65633dcd2df3c5095b5d230c387c78d7cb0de8.json',sha256:'51ec9482a97ae37bc3b157494f65633dcd2df3c5095b5d230c387c78d7cb0de8',bytes:9842}} as const;
const ID='municipality/bremen/micro-mh-history2023',UNIT={zh:'千人',en:'thousand persons',de:'Tausend Personen'};
async function read(ref:{path:string;sha256:string;bytes:number},fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>,signal:AbortSignal){signal.throwIfAborted();const bytes=await fetchBytes(ref.path,signal);signal.throwIfAborted();if(bytes.byteLength!==ref.bytes||bytes.byteLength>8*1024*1024)throw Error('Bremen optional reference size');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==ref.sha256)throw Error('Bremen optional reference hash');signal.throwIfAborted();return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
/** Separate optional document, never append a ninth scope to the existing eight-scope city file. */
export function createBremen2023Reference(fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>){let accepted:{observation:Observation;rule:SourceRule}|undefined;return {async load(city:string,signal:AbortSignal){if(city!=='bremen')return;signal.throwIfAborted();if(accepted)return accepted;const raw=await read(BREMEN2023_REFS.metric,fetchBytes,signal),source=await read(BREMEN2023_REFS.rules,fetchBytes,signal),scopes=officialMunicipalScopes(raw,'bremen');if(scopes.length!==1||scopes[0].id!==ID||scopes[0].metrics.length!==1||source.rules?.length!==1)throw Error('Bremen source scope/schema');const metric=scopes[0].metrics[0] as AreaMetric&{source_column?:string;source_row_group?:string;source_age_scope?:string;source_result_status?:string;source_population_basis?:string;derived?:boolean};if(metric.value!==246||metric.unit!=='thousand persons'||metric.year!==2023||metric.reference_date!=='2023'||metric.source_column!=='Bremen Stadt'||metric.source_row_group!=='Insgesamt'||metric.source_age_scope!=='all ages'||metric.source_population_basis!=='population in main-residence households'||metric.derived!==false)throw Error('Bremen source precision/scope');const rule=source.rules[0] as SourceRule,observation=referenceObservation({city:'bremen',scope:'municipal',scopeId:ID,scopeName:scopes[0].name as Text},metric as unknown as Observation['metric'],[rule]);if(!observation||rule.requireVisibleLimitation!==true||!rule.visibleLimitation||!['zh','en','de'].every(l=>typeof rule.visibleLimitation?.[l as keyof Text]==='string'&&rule.visibleLimitation[l as keyof Text].trim()))throw Error('Bremen source limitation');signal.throwIfAborted();accepted={observation,rule};return accepted;},destroy(){accepted=undefined;}};}
/** One historical municipal measure. View-only localized unit, no multiplication/share/cohort index. */
export function renderBremen2023Reference(host:HTMLElement,observation:Observation,rule:SourceRule,locale:'zh'|'en'|'de'){
 if(observation.city!=='bremen'||observation.scope!=='municipal'||observation.scopeId!==ID||observation.metric.value!==246||observation.metric.unit!=='thousand persons'||!rule.visibleLimitation)throw Error('Bremen reference view invalid');const metric=observation.metric as unknown as AreaMetric,section=document.createElement('section');section.className='bremen2023-optional-reference';const put=(tag:string,text:string)=>{const p=document.createElement(tag);p.textContent=text;section.append(p);return p;};put('h4',metric.label[locale]);put('p',({zh:'仅不来梅市2023抽样历史参考 · 非所选分区 · 非2024/2025登记值',en:'Bremen city2023survey history only · not selected area or2024/2025register data',de:'Nur StadtBremen2023Erhebung · keinTeilgebiet oderRegisterwert2024/2025'})[locale]);put('p',rule.visibleLimitation[locale]);put('p',new Intl.NumberFormat(locale).format(246)+' '+UNIT[locale]+' · 2023');appendMetricVisual(section,{...metric,unit:UNIT[locale]},locale,{scope:'municipal'});const details=document.createElement('details'),summary=document.createElement('summary'),source=document.createElement('a');summary.textContent=({zh:'原始来源与口径',en:'Original source and definition',de:'Originalquelle und Definition'})[locale];source.textContent=metric.source_name;source.href=metric.source_url;source.target='_blank';source.rel='noopener noreferrer';details.append(summary,source);section.append(details);host.append(section);return section;
}

export const BREMEN_RENT_REFS={metric:{path:'/safety/geography/reference-optional/bremen-1e7492da705738719b3821045dc7d503b773598ae1ad5a92a1f603a4e47d0a80.json',sha256:'1e7492da705738719b3821045dc7d503b773598ae1ad5a92a1f603a4e47d0a80',bytes:6275},rules:{path:'/safety/geography/reference-optional/bremen-f2a742f11a719f2910f154c8a9bf69076030f49b96768a5595a4e33ab069db7b.json',sha256:'f2a742f11a719f2910f154c8a9bf69076030f49b96768a5595a4e33ab069db7b',bytes:2218}} as const;
function createBremenTwoOptionalReference(fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>){const history=createBremen2023Reference(fetchBytes);let rent:{observation:Observation;rule:SourceRule}|undefined;return {async load(city:string,signal:AbortSignal){if(city!=='bremen')return;const mh=await history.load(city,signal);if(!rent){const raw=await read(BREMEN_RENT_REFS.metric,fetchBytes,signal),source=await read(BREMEN_RENT_REFS.rules,fetchBytes,signal),scopes=officialMunicipalScopes(raw,'bremen');if(scopes.length!==1||scopes[0].id!=='municipality/bremen/asking-rent-h1-2025'||scopes[0].metrics.length!==1||source.rules?.length!==1)throw Error('Bremen rent source scope');const metric=scopes[0].metrics[0] as AreaMetric&{source_sample_size?:number;reference_period?:string;source_statistic?:string;derived?:boolean};if(metric.value!==11.17||metric.source_sample_size!==3358||metric.unit!=='€/m²'||metric.year!==2025||metric.reference_period!=='2025 H1'||metric.source_statistic!=='median'||metric.derived!==false)throw Error('Bremen rent source method');const rule=source.rules[0] as SourceRule,observation=referenceObservation({city:'bremen',scope:'municipal',scopeId:scopes[0].id,scopeName:scopes[0].name as Text},metric as unknown as Observation['metric'],[rule]);if(!observation)throw Error('Bremen rent literal match');signal.throwIfAborted();rent={observation,rule};}return {observations:[mh!.observation,rent.observation],rules:[mh!.rule,rent.rule]};},destroy(){history.destroy();rent=undefined;}};}
export function renderBremenOptionalReference(host:HTMLElement,observation:Observation,rule:SourceRule,locale:'zh'|'en'|'de'){
 if(observation.scopeId===ID)return renderBremen2023Reference(host,observation,rule,locale);
 if(observation.scopeId===BREMEN_AGE2015_ID)return renderBremenAge2015Reference(host,observation,rule,locale);
 if(observation.city!=='bremen'||observation.scopeId!=='municipality/bremen/asking-rent-h1-2025'||observation.metric.value!==11.17)throw Error('Bremen rent view invalid');const m=observation.metric as unknown as AreaMetric&{source_sample_size:number},section=document.createElement('section');section.className='bremen-rent-h1-optional-reference';const put=(tag:string,s:string)=>{const p=document.createElement(tag);p.textContent=s;section.append(p);return p;};put('h4',m.label[locale]);put('p',m.definition[locale]);put('p',datedMetricValue(m,locale));appendMetricVisual(section,m,locale,{scope:'municipal'});
 const sampleLabel={zh:'中位数所用样本：租赁报价数（不是独立租户）',en:'Median supporting sample: rental offers (not unique tenants)',de:'Stichprobe zum Median: Mietangebote (keine eindeutigen Mietparteien)'},sampleUnit={zh:'条报价',en:'offers',de:'Angebote'},sample={...m,value:m.source_sample_size,unit:sampleUnit[locale],label:sampleLabel,definition:{zh:'原文2025上半年全市3,358条报价，仅为中位数的来源样本量；不新增独立指标、不推租户或住户人数。',en:'Original H1 2025 city sample3,358offers, supporting the published median; not a new independent metric or tenant/household count.',de:'Originale städtische Stichprobe1.Halbjahr2025:3.358Angebote zum Median; keine neue unabhängige Kennzahl oder Mietparteien-/Haushaltszahl.'}};put('p',new Intl.NumberFormat(locale).format(m.source_sample_size)+' '+sampleUnit[locale]+' · '+({zh:'2025上半年',en:'H1 2025',de:'1. Halbjahr 2025'})[locale]);appendMetricVisual(section,sample,locale,{scope:'municipal'});const a=put('a',m.source_name)as HTMLAnchorElement;a.href=m.source_url;a.target='_blank';a.rel='noopener noreferrer';host.append(section);return section;
}

export const BREMEN_AGE2015_REFS={
  "metric": {
    "path": "/safety/geography/reference-optional/bremen-1dabf477ba3330471a58c9187d57acd4523bba3bd3c3b40ee2f4076752133af7.json",
    "sha256": "1dabf477ba3330471a58c9187d57acd4523bba3bd3c3b40ee2f4076752133af7",
    "bytes": 42284
  },
  "rules": {
    "path": "/safety/geography/reference-optional/bremen-c52a419c43b550a037bb8d4775f52fb656bbd3cfd03e6a68dfd916b16a192dd0.json",
    "sha256": "c52a419c43b550a037bb8d4775f52fb656bbd3cfd03e6a68dfd916b16a192dd0",
    "bytes": 17464
  }
} as const;
const BREMEN_AGE2015_ID='municipality/bremen/census2011-updating-age-history2015';
/** Extend the existing two-reference loader; all three documents retain separate original scopes. */
export function createBremenOptionalReference(fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>){
 const firstTwo=createBremenTwoOptionalReference(fetchBytes);let age:{observations:Observation[];rules:SourceRule[]}|undefined,destroyed=false;
 return {async load(city:string,signal:AbortSignal){if(city!=='bremen')return;signal.throwIfAborted();if(destroyed)throw Error('Bremen optional destroyed');const base=await firstTwo.load(city,signal);signal.throwIfAborted();if(!base||destroyed)throw Error('Bremen optional unavailable');
  if(!age){const raw=await read(BREMEN_AGE2015_REFS.metric,fetchBytes,signal),packet=await read(BREMEN_AGE2015_REFS.rules,fetchBytes,signal),scopes=officialMunicipalScopes(raw,'bremen');if(scopes.length!==1||scopes[0].id!==BREMEN_AGE2015_ID||scopes[0].metrics.length!==8||packet.rules?.length!==8)throw Error('Bremen age scope/schema');
   const rules=packet.rules as SourceRule[],observations:Observation[]=[],keys=new Set<string>();for(const metric of scopes[0].metrics){const m=metric as AreaMetric&{source_population_basis?:string;source_table?:string;source_same_table_population?:number;source_age_count?:number;source_age_lower_inclusive?:number;source_age_upper_exclusive?:number;derived?:boolean};if(m.year!==2015||m.reference_date!=='2015-12-31'||m.source_population_basis!=='Census2011-based population updating'||m.source_table!=='Tab.1; year-end citypopulation'||m.source_same_table_population!==557464||m.derived!==true||!['','%'].includes(m.unit))throw Error('Bremen age source basis');const o=referenceObservation({city:'bremen',scope:'municipal',scopeId:BREMEN_AGE2015_ID,scopeName:scopes[0].name as Text},m as unknown as Observation['metric'],rules);if(!o||keys.has(o.conceptId))throw Error('Bremen age source match');keys.add(o.conceptId);observations.push(o);}
   signal.throwIfAborted();if(destroyed)throw Error('Bremen optional destroyed');age={observations,rules};
  }return {observations:[...base.observations,...age.observations],rules:[...base.rules,...age.rules]};
 },destroy(){destroyed=true;firstTwo.destroy();age=undefined;}};
}
/** Original historical values and definitions, always visible; one municipal figure per metric, no native cohort. */
function renderBremenAge2015Reference(host:HTMLElement,o:Observation,rule:SourceRule,locale:'zh'|'en'|'de'){
 if(o.city!=='bremen'||o.scope!=='municipal'||o.scopeId!==BREMEN_AGE2015_ID||o.metric.year!==2015||o.metric.reference_date!=='2015-12-31'||!referenceObservation({city:'bremen',scope:'municipal',scopeId:o.scopeId,scopeName:o.scopeName},o.metric,[rule]))throw Error('Bremen age view invalid');
 const m=o.metric as unknown as AreaMetric,section=document.createElement('section');section.className='bremen-age2015-optional-reference';const put=(tag:string,text:string)=>{const p=document.createElement(tag);p.textContent=text;section.append(p);return p;};put('h4',m.label[locale]);put('p',o.scopeName[locale]);put('p',m.definition[locale]);put('p',datedMetricValue(m,locale));appendMetricVisual(section,m,locale,{scope:'municipal'});const link=put('a',m.source_name)as HTMLAnchorElement;link.href=m.source_url;link.target='_blank';link.rel='noopener noreferrer';host.append(section);return section;
}
