export type ElectionChoice={id:string;type:'federal'|'state'|'municipal';year:2025|2026;label:Record<'zh'|'en'|'de',string>};
type Locale='zh'|'en'|'de';
const COPY={
 zh:{title:'选举地图',toggle:'显示选举地图',type:'选举类型',instance:'年份与场次',federal:'联邦议院',state:'州议会',municipal:'地方议会',empty:'该城市尚无已核验的2025/2026选举图层。',loading:'正在加载选举图层…',failed:'选举图层加载失败；关闭后重新开启可重试。',note:'选举图层独立于警方公告月份和场所筛选。颜色与网格表示该分块的选举结果，不表示犯罪风险。各场次使用各自的已核验统计范围；网格只是显示纹理。'},
 en:{title:'Election map',toggle:'Show election map',type:'Election type',instance:'Year and election',federal:'Federal parliament',state:'State parliament',municipal:'Local council',empty:'No verified 2025/2026 election layer is connected for this city yet.',loading:'Loading election layer…',failed:'Election layer could not be loaded. Turn it off and on to retry.',note:'The election layer is independent of police-report months and place filters. Colours and grids represent election results in each area, not crime risk. Each election uses its own verified reporting geography; the grid is only a display texture.'},
 de:{title:'Wahlkarte',toggle:'Wahlkarte anzeigen',type:'Wahlart',instance:'Jahr und Wahl',federal:'Bundestag',state:'Landtag',municipal:'Kommunalwahl',empty:'Für diese Stadt ist noch keine geprüfte Wahlebene 2025/2026 angebunden.',loading:'Wahlebene wird geladen…',failed:'Wahlebene konnte nicht geladen werden. Zum Wiederholen aus- und einschalten.',note:'Die Wahlebene ist unabhängig vom Monat der Polizeimeldungen und den Ortsfiltern. Farben und Gitter zeigen Wahlergebnisse des Gebiets, kein Kriminalitätsrisiko. Jede Wahl verwendet ihren eigenen geprüften Gebietsbezug; das Gitter ist nur ein Darstellungsmuster.'}
};
export function electoralControls(host:HTMLElement,locale:Locale,onChange:(enabled:boolean,id:string,overlayIds:ReadonlySet<string>)=>void,onRetry?:()=>void){
 const c=COPY[locale],section=document.createElement('section');section.className='electoral-controls';
 const heading=document.createElement('h3');heading.textContent=c.title;
 const toggleLabel=document.createElement('label'),toggle=document.createElement('input');toggle.type='checkbox';toggle.disabled=true;toggleLabel.append(toggle,document.createTextNode(' '+c.toggle));
 const typeLabel=document.createElement('label'),type=document.createElement('select');type.setAttribute('aria-label',c.type);typeLabel.append(document.createTextNode(c.type),type);
 const instanceLabel=document.createElement('label'),instance=document.createElement('select');instance.setAttribute('aria-label',c.instance);instanceLabel.append(document.createTextNode(c.instance),instance);
 const status=document.createElement('p');status.className='hint';status.setAttribute('role','status');status.textContent=c.loading;
 const note=document.createElement('p');note.className='hint';note.textContent=c.note;
 const overlays=document.createElement('fieldset');overlays.className='electoral-overlays';const overlayLegend=document.createElement('legend');overlayLegend.textContent=({zh:'叠加其他选举边界',en:'Overlay other election boundaries',de:'Weitere Wahlgrenzen überlagern'})[locale];overlays.append(overlayLegend);section.append(heading,toggleLabel,typeLabel,instanceLabel,overlays,status,note);host.append(section);const retry=document.createElement('button');retry.type='button';retry.textContent=({zh:'重试加载选举地图',en:'Retry election map',de:'Wahlkarte erneut laden'})[locale];retry.hidden=true;retry.onclick=()=>{retry.hidden=true;onRetry?.();};section.append(retry);let choices:ElectionChoice[]=[];const overlayInputs=new Map<string,HTMLInputElement>();
 const update=()=>{type.disabled=instance.disabled=!toggle.checked||!choices.length;for(const [id,input]of overlayInputs){input.disabled=!toggle.checked||id===instance.value;if(id===instance.value)input.checked=false;}onChange(toggle.checked,instance.value,new Set([...overlayInputs].filter(([,input])=>input.checked&&!input.disabled).map(([id])=>id)));};
 const fill=()=>{const rows=choices.filter(e=>e.type===type.value);instance.replaceChildren(...rows.map(e=>{const option=document.createElement('option');option.value=e.id;option.textContent=e.label[locale];return option;}));const preferred=rows.find(e=>e.type==='federal'&&e.year===2025);if(preferred)instance.value=preferred.id;};
 toggle.onchange=update;type.onchange=()=>{fill();update();};instance.onchange=update;
 return {setChoices(values:ElectionChoice[]){retry.hidden=true;const previousType=type.value,previousId=instance.value,previousOverlays=new Set([...overlayInputs].filter(([,input])=>input.checked).map(([id])=>id));choices=values;overlayInputs.clear();overlays.replaceChildren(overlayLegend);for(const e of values){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=e.id;input.checked=previousOverlays.has(e.id);input.disabled=true;input.onchange=update;label.append(input,document.createTextNode(' '+e.label[locale]));overlays.append(label);overlayInputs.set(e.id,input);}overlays.hidden=values.length<2;const kinds=[...new Set(values.map(e=>e.type))];type.replaceChildren(...kinds.map(k=>{const option=document.createElement('option');option.value=k;option.textContent=c[k];return option;}));if(kinds.includes(previousType as ElectionChoice['type']))type.value=previousType;else if(kinds.includes('federal'))type.value='federal';fill();if(values.some(e=>e.id===previousId&&e.type===type.value))instance.value=previousId;for(const [id,input]of overlayInputs){input.disabled=!toggle.checked||id===instance.value;if(id===instance.value)input.checked=false;}toggle.disabled=!choices.length;type.disabled=instance.disabled=!toggle.checked||!choices.length;status.textContent=choices.length?'':c.empty;},loading(){retry.hidden=true;status.textContent=c.loading;},failed(){retry.hidden=!onRetry;status.textContent=({zh:'选举地图未能加载，请重试；这不表示本市没有选举数据。',en:'The election map could not be loaded. Please retry; this does not mean the city has no election data.',de:'Die Wahlkarte konnte nicht geladen werden. Versuchen Sie es erneut; dies bedeutet nicht, dass keine Wahldaten für die Stadt vorliegen.'})[locale];},status(text:string){status.textContent=text;},destroy(){section.remove();}};
}
