import {officialRegionalScopes} from './area-metrics';
import {referenceObservation,type SourceRule} from './reference-registry-matcher';
import type {Observation,ReferenceMetric,Text} from './reference-fallback';
export const HANNOVER_REGIONAL_REFS={metrics:{path:'/safety/geography/official-regional-scope-metrics.json',sha256:'b1ff947f188338362ff97f8fe8f69806571badf94d200c6404823afa67a689f6',bytes:4359},rules:{path:'/safety/geography/reference-regional/hannover-ba202609-rules.json',sha256:'6287cce36c0471870ac6fade1307530320e2957dacf6b65fa3938df91b1a9edc',bytes:9039},membership:{path:'/safety/geography/reference-regional/hannover-membership.json',sha256:'8ae4c49f7680001bc067071310ae5cd435c17e207aba4a076572e0ed31768279',bytes:70564}} as const;
const SCOPE='region/hannover/03241000/ba-unemployment202609',CITY_AGS='03241001',REGION_CODE='03241000',SOURCE_SHA='ad4ed583ac86485a594d6aa7cb2d023c05c79fd19c18983d15e66a122c0568f1',CITY_BOUNDARY_SHA='5d124da9638515bc2262cf36a3105385a882218d191994ffb8aea8701d2a528a';
const LAYERS:Record<string,string>={level1:'eac74e9fc38a7ec95e7ae3769574befa337582fe7f2210942f6fa81a1608b1dd',level2:'32127394449fc331076dee9814738fc26bf5a15e10c51055dca19e49320b1808'};
export interface RegionalSelection {city:string;nativeLevel:string;selectedNativeAreaId:string;currentGeometrySha256:string;}
export interface RegionalReferences {observations:Observation[];rules:SourceRule[];limitation:Text;}
export class RegionalReferenceError extends Error {readonly code:string;constructor(code:string){super('Regional reference unavailable: '+code);this.code=code;this.name='RegionalReferenceError';}}
function fail(code:string):never{throw new RegionalReferenceError(code)}
const hash=(s:unknown)=>typeof s==='string'&&/^[a-f0-9]{64}$/.test(s);
const localized=(s:any):s is Text=>s&&['zh','en','de'].every(k=>typeof s[k]==='string'&&s[k].trim());
/** Input JSON must be authenticated through loadHannoverRegionalReferences. Exported for source-contract tests. */
export function parseHannoverRegionalReferences(metricsRaw:any,rulesRaw:any,membership:any,s:RegionalSelection):RegionalReferences {
 if(s.city!=='hannover'||!Object.hasOwn(LAYERS,s.nativeLevel)||s.currentGeometrySha256!==LAYERS[s.nativeLevel])fail('selection');
 if(membership?.regionScopeId!==SCOPE||membership.BA_source_code!==REGION_CODE||membership.Kreiscode!=='03241'||membership.not_city_rate!==true||membership.includeInNativeStatistics!==false||membership.regionPolygonGenerated!==false||membership.nativeValuesAllocated!==false||!Array.isArray(membership.members)||membership.members.length!==64||!Array.isArray(membership.memberAreaIds)||membership.memberAreaIds.length!==64)fail('membership-envelope');
 if(membership.city_in_region?.source_statement!=='Dazu gehört die Landeshauptstadt Hannover'||membership.city_in_region?.original_html_sha256!=='cda0411f31db51db9c1dd684928830295dbe4035b753e0afe14c45ea10f077d6'||membership.native_within_city?.official_source_sha256!=='33ffdd7bb7845154c00526a807b40803c0d8d64729dd1ca5c43fa1bfc62e696b'||membership.native_within_city?.source_join_receipt_sha256!=='2c62f73ed7a9274cb4b32850c184cf4f4d2262bc6c728eed24bb9a6a97ebd63e'||membership.native_within_city?.municipality_boundary_sha256!==CITY_BOUNDARY_SHA||membership.native_within_city?.whole_polygon_containment!==true)fail('official-membership');
 const ids=new Set<string>(),levelMembers:string[]=[];let level1=0,level2=0;
 for(const m of membership.members){const p=m?.geometryProof;if(typeof m?.nativeAreaId!=='string'||ids.has(m.nativeAreaId)||!Object.hasOwn(LAYERS,m.nativeLevel)||m.cityAGS!==CITY_AGS||m.cityId!=='osm/relation/59418'||m.regionBARawCode!==REGION_CODE||m.regionKreisCode!=='03241'||!p||p.nativeLayerSha256!==LAYERS[m.nativeLevel]||!hash(p.nativeGeometrySha256)||p.municipalityBoundarySha256!==CITY_BOUNDARY_SHA||p.sameSourcePbfSha256!=='0284f5ca805a651ecbd0787112fcc9889d6fd2c192a33940b14c1cda22c8ad9e'||p.wholeNativePolygonCoveredByCity!==true||p.outsideCityDifferenceEmpty!==true||!m.officialCitySubdivision?.method)fail('native-membership');ids.add(m.nativeAreaId);m.nativeLevel==='level1'?level1++:level2++;if(m.nativeLevel===s.nativeLevel)levelMembers.push(m.nativeAreaId);}
 if(level1!==51||level2!==13||new Set(membership.memberAreaIds).size!==64||membership.memberAreaIds.some((id:string)=>!ids.has(id))||!levelMembers.includes(s.selectedNativeAreaId))fail('selected-membership');
 const scopes=officialRegionalScopes(metricsRaw,'hannover');if(scopes.length!==1||scopes[0].id!==SCOPE||scopes[0].scope_type!=='Region'||scopes[0].metrics.length!==1)fail('regional-source');const metric=scopes[0].metrics[0] as typeof scopes[0]['metrics'][0]&{source_sha256?:string;source_native_code?:string};
 if(metric.source_sha256!==SOURCE_SHA||metric.source_native_code!==REGION_CODE||metric.value!==8.1||metric.reference_date!=='2026-09'||metric.year!==2026||metric.unit!=='%')fail('regional-value');
 const rules=rulesRaw?.rules as SourceRule[];if(!Array.isArray(rules)||rules.length!==1||rules[0].city!=='hannover'||rules[0].scope!=='regional'||rules[0].scopeId!==SCOPE||rules[0].levels.length!==0||rules[0].equals.source_native_code!==REGION_CODE||rules[0].equals.source_sha256!==SOURCE_SHA)fail('regional-rule');const full=rules[0] as SourceRule&{membershipEvidence?:string;memberAreaIds?:string[];limitation?:Text};
 if(!localized(full.limitation)||typeof full.membershipEvidence!=='string'||!full.membershipEvidence.trim()||!Array.isArray(full.memberAreaIds)||full.memberAreaIds.length!==64||new Set(full.memberAreaIds).size!==64||full.memberAreaIds.some(id=>!ids.has(id)))fail('rule-membership');
 const original=referenceObservation({city:s.city,scope:'regional',scopeId:SCOPE,scopeName:scopes[0].name as Text},metric as unknown as ReferenceMetric,rules);if(!original)fail('source-match');
 return {observations:[{...original,memberAreaIds:levelMembers,membershipEvidence:full.membershipEvidence}],rules,limitation:full.limitation};
}
export async function loadHannoverRegionalReferences(options:{selection:RegionalSelection;signal:AbortSignal;fetchBytes:(path:string,signal:AbortSignal,policy?:'no-store')=>Promise<Uint8Array>}):Promise<RegionalReferences>{
 const values:any[]=[];for(const [key,ref] of Object.entries(HANNOVER_REGIONAL_REFS)){options.signal.throwIfAborted();const bytes=await options.fetchBytes(ref.path,options.signal,key==='metrics'?'no-store':undefined);options.signal.throwIfAborted();if(bytes.byteLength!==ref.bytes||bytes.byteLength>8*1024*1024)fail('bytes');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),b=>b.toString(16).padStart(2,'0')).join('');options.signal.throwIfAborted();if(digest!==ref.sha256)fail('sha');values.push(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)));}
 return parseHannoverRegionalReferences(values[0],values[1],values[2],options.selection);
}
export const regionalReferenceCopy={zh:{badge:'较大区域参考值 · 非全市或所选分区实测',note:'汉诺威大区包含汉诺威市及另外20个市镇；8.1%为整个大区2026年9月失业率。'},en:{badge:'Wider-region reference · not a municipality or local measurement',note:'Region Hannover includes Hannover city and 20 other municipalities; 8.1% is the September 2026 unemployment rate for the whole region.'},de:{badge:'Referenz der größeren Region · kein Stadt- oder Teilgebietsmesswert',note:'Die Region Hannover umfasst die Stadt Hannover und 20 weitere Kommunen; 8,1 % ist die Arbeitslosenquote der gesamten Region im September 2026.'}} as const;
