import {appendMetricVisual} from './metric-visualization';
import type {AreaMetric} from './area-metrics';
import {loadSemanticProjection,type Context,type Metric,type ProjectedView,type Locale} from './lis-semantic-projection';
export type {Context,ProjectedView};
export const LIS_PROJECTION_REF={path:'/safety/geography/reference-semantic/leipzig-lis-da3542a416e09c891dca1c55c4bf2f8f382168f1e9e06930464798b62d4670ff.json',sha256:'da3542a416e09c891dca1c55c4bf2f8f382168f1e9e06930464798b62d4670ff',bytes:56340} as const;
const TRIGGERS=[['791a38e41356556ca750cd9de3b2f1b41d21587e569d0b5016aaa76f599e91dd','https://statistik.leipzig.de/statdist/table.aspx?cat=13&rub=1&item=197'],['fe1fb448df095de7d3b90b357fa0a18565b87ffeac5d1c496e79ecbe6d72f775','https://statistik.leipzig.de/statdist/table.aspx?cat=13&rub=1&item=200'],['1344dfeafa018b2df0465f7b43d95e18b1d3c27b3ce039691a6f3c4fa1d82e49','https://statistik.leipzig.de/statdist/table.aspx?cat=13&rub=1']] as const;
const COPY={zh:{pending:'受限来源指标正在核对；核实前暂不显示原题名数值。',withheld:'该受限来源观测与已核实投影不符，暂不显示；不能据此判断无公布。'},en:{pending:'A limited source indicator is being verified; its raw-captioned value is withheld until qualification.',withheld:'This limited source observation does not match the reviewed projection and is withheld; this does not establish non-publication.'},de:{pending:'Die eingeschränkte Quellenkennzahl wird geprüft; der Wert unter dem Rohquelltitel bleibt bis zur Prüfung verborgen.',withheld:'Dieser eingeschränkte Quellenwert entspricht nicht der geprüften Projektion und bleibt verborgen; das belegt keine Nichtveröffentlichung.'}};
export type ProjectionState={status:'regular'}|{status:'pending'|'withheld'}|{status:'projected';view:ProjectedView};
export interface LISProjectionGate {needs:(context:Context,metric:Metric)=>boolean;ensure:(signal:AbortSignal)=>Promise<void>;peek:(context:Context,metric:Metric)=>ProjectionState;render:(host:HTMLElement,context:Context,metric:Metric,locale:Locale,format:(m:Metric,l:Locale)=>string,visualScope?:'native'|'context')=>ProjectionState;destroy:()=>void;}
/** Triggers only withhold/load known source snapshots; the owner's packet alone qualifies IDs/values/fields. */
export function createLISProjectionGate(fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>):LISProjectionGate{
 let projection:Awaited<ReturnType<typeof loadSemanticProjection>>|undefined,destroyed=false;
 const needs=(context:Context,metric:Metric)=>context.city==='leipzig'&&['level1','level2'].includes(context.level)&&TRIGGERS.some(([sha,url])=>metric.source_sha256===sha&&metric.source_url===url);
 const peek=(context:Context,metric:Metric):ProjectionState=>{if(!needs(context,metric))return {status:'regular'};if(!projection)return {status:'pending'};const result=projection.project(context,metric);return result.status==='projected'?result:{status:'withheld'};};
 return {needs,peek,async ensure(signal){if(destroyed)throw Error('Projection gate destroyed');signal.throwIfAborted();if(projection)return;const bytes=await fetchBytes(LIS_PROJECTION_REF.path,signal);signal.throwIfAborted();if(bytes.byteLength!==LIS_PROJECTION_REF.bytes||bytes.byteLength>8*1024*1024)throw Error('Projection bytes invalid');const accepted=await loadSemanticProjection(new TextDecoder('utf-8',{fatal:true}).decode(bytes),LIS_PROJECTION_REF.sha256);signal.throwIfAborted();if(destroyed)throw Error('Projection gate destroyed');projection=accepted;},render(host,context,metric,locale,format,visualScope='context'){const state=peek(context,metric);if(state.status==='regular')return state;if(state.status==='projected'&&projection?.render(host,state.view,locale,format,(detached,view,l)=>{const displayMetric={...view.metric,label:view.displayLabel} as unknown as AreaMetric;appendMetricVisual(detached,displayMetric,l,{scope:visualScope});}).status==='rendered')return state;const note=document.createElement('p');note.className='lis-projection-withheld';note.textContent=COPY[locale][state.status==='pending'?'pending':'withheld'];host.append(note);return {status:state.status==='pending'?'pending':'withheld'};},destroy(){destroyed=true;projection=undefined;}};
}
