import {containsPosition} from './geography-position.ts';
import type {Map as MapView,GeoJSONSource} from 'maplibre-gl';
type Locale='zh'|'en'|'de';
const COPY={zh:{recordType:'记录类型',shop:'店铺／餐饮记录',building:'建筑',road:'道路',place:'OSM场所',position:'手动选中位置',unnamed:'OSM未提供名称',type:'类型',address:'地址',hours:'营业时间',website:'网站',operator:'运营方',source:'查看OSM来源',note:'只显示当前地图数据中已有的OSM字段；建筑与店铺记录分别处理。轮廓是当前地图切片中的显示范围。',pointNote:'这是手动选点，不是警方事件坐标。',coordinate:'经纬度'},en:{recordType:'Record type',shop:'Shop / food-place record',building:'Building',road:'Road',place:'OSM place',position:'Manually selected position',unnamed:'No name supplied by OSM',type:'Type',address:'Address',hours:'Opening hours',website:'Website',operator:'Operator',source:'View OSM source',note:'Only existing OSM fields in the loaded map data are shown. Building and shop records remain separate. The outline is the geometry displayed by the current map tile.',pointNote:'This is a manually selected point, not a police-event coordinate.',coordinate:'Longitude / latitude'},de:{recordType:'Datensatztyp',shop:'Geschäft / Gastronomieeintrag',building:'Gebäude',road:'Straße',place:'OSM-Ort',position:'Manuell gewählter Kartenpunkt',unnamed:'Kein Name in OSM angegeben',type:'Typ',address:'Adresse',hours:'Öffnungszeiten',website:'Website',operator:'Betreiber',source:'OSM-Quelle ansehen',note:'Nur vorhandene OSM-Felder der geladenen Kartendaten. Gebäude- und Geschäftsdatensätze bleiben getrennt. Der Umriss ist die Geometrie der aktuellen Kartenkachel.',pointNote:'Manuell gewählter Punkt, keine Koordinate eines Polizeiereignisses.',coordinate:'Längengrad / Breitengrad'}};
function value(v:unknown){return typeof v==='string'&&v.trim()&&v.length<=1000?v.trim():typeof v==='number'&&Number.isFinite(v)?String(v):undefined;}
export function osmInformation(feature:any,locale:Locale):{kind:'building'|'road'|'place';name?:string;type?:string;address?:string;hours?:string;operator?:string;website?:string;source:string}{
 const p=feature?.properties??{},kind:'building'|'road'|'place'=feature?.layer?.id?.includes('building')||(!p.shop&&!p.amenity&&p.building)?'building':p.highway||feature?.layer?.id?.includes('street')?'road':'place';
 const name=value(p['name_'+locale])??value(p['name:'+locale])??value(p.name),type=[p.shop,p.amenity,p.office,p.tourism,p.building,p.highway,p.class].map(value).find(Boolean);
 const address=value(p.address)??[p['addr:street']??p.addr_street,p['addr:housenumber']??p.addr_housenumber,p['addr:postcode']??p.addr_postcode,p['addr:city']??p.addr_city].map(value).filter(Boolean).join(' ');
 const osm=value(p.id)?.match(/^osm\/(node|way|relation)\/(\d+)$/);const website=value(p.website??p['contact:website']);let safeWebsite:string|undefined;if(website){try{const url=new URL(website);if(['http:','https:'].includes(url.protocol)&&!url.username&&!url.password)safeWebsite=url.href;}catch{}}
 return {kind,name,type,address:address||undefined,hours:value(p.opening_hours),operator:value(p.operator),website:safeWebsite,source:osm?'https://www.openstreetmap.org/'+osm[1]+'/'+osm[2]:'https://www.openstreetmap.org/copyright'};
}
/** Select only existing building components under the click; grouped tile features are not one building. */
export function clickedBuildingGeometry(feature:any,point?:number[]){
 const geometry=feature?.geometry;
 if(!point||osmInformation(feature,'en').kind!=='building')return geometry;
 if(geometry?.type==='Polygon')return containsPosition(geometry,point)?geometry:undefined;
 if(geometry?.type!=='MultiPolygon')return geometry;
 const parts=geometry.coordinates.filter((coordinates:any)=>containsPosition({type:'Polygon',coordinates},point));
 return parts.length===1?{type:'Polygon',coordinates:parts[0]}:parts.length?{type:'MultiPolygon',coordinates:parts}:undefined;
}
/** One selected geometry, three fixed layers; no queries or inferred occupant associations. */
export function installOsmClickInspection(map:MapView,locale:Locale,onInspect:(panel:HTMLElement)=>void){
 const c=COPY[locale],source='osm-click-inspection',ids=[source+'-fill',source+'-line',source+'-point'];const empty=()=>({type:'FeatureCollection' as const,features:[] as any[]});
 map.addSource(source,{type:'geojson',data:empty()});map.addLayer({id:ids[0],type:'fill',source,filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#e2bd55','fill-opacity':.22}});map.addLayer({id:ids[1],type:'line',source,filter:['!=',['geometry-type'],'Point'],paint:{'line-color':'#e2bd55','line-width':2.5}});map.addLayer({id:ids[2],type:'circle',source,filter:['==',['geometry-type'],'Point'],paint:{'circle-color':'#e2bd55','circle-radius':6,'circle-stroke-color':'#fff','circle-stroke-width':2}});
 function inspect(feature:any,point?:number[]){const selectedGeometry=feature?clickedBuildingGeometry(feature,point):undefined;const object=selectedGeometry?feature:undefined;const panel=document.createElement('section');panel.className='osm-click-information';panel.setAttribute('data-osm-highlight-polygons',String(selectedGeometry?.type==='MultiPolygon'?selectedGeometry.coordinates.length:selectedGeometry?.type==='Polygon'?1:0));const info=object?osmInformation(object,locale):undefined;const h=document.createElement('h3');h.textContent=info?.name??(info?c[info.kind]+' · '+c.unnamed:c.position);panel.append(h);
  const row=(label:string,text?:string)=>{if(!text)return;const p=document.createElement('p');p.textContent=label+': '+text;panel.append(p);};
  if(info){row(c.recordType,info.kind==='building'?c.building:info.kind==='road'?c.road:object?.properties?.base_shop_kind||object?.properties?.shop?c.shop:c.place);row(c.type,info.type);row(c.address,info.address);row(c.hours,info.hours);row(c.operator,info.operator);const note=document.createElement('p');note.textContent=c.note;panel.append(note);for(const [label,url]of [[c.source,info.source],[c.website,info.website]] as const)if(url){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener noreferrer';panel.append(a);}}
  else if(point){row(c.coordinate,point.map(n=>n.toFixed(5)).join(', '));const note=document.createElement('p');note.textContent=c.pointNote;panel.append(note);}
  const data=object?{type:'Feature',geometry:selectedGeometry,properties:{}}:point?{type:'Feature',geometry:{type:'Point',coordinates:point},properties:{}}:undefined;(map.getSource(source)as GeoJSONSource).setData(data?{type:'FeatureCollection',features:[data]}:empty());onInspect(panel);return {panel,geometry:selectedGeometry};
 }
 return {inspect,highlight(feature:any){(map.getSource(source)as GeoJSONSource).setData(feature?{type:'FeatureCollection',features:[{type:'Feature',geometry:feature.geometry,properties:{}}]}:empty());},clear(){(map.getSource(source)as GeoJSONSource).setData(empty());},destroy(){for(const id of [...ids].reverse())if(map.getLayer(id))map.removeLayer(id);if(map.getSource(source))map.removeSource(source);}};
}
