import {stopDescriptor,type StopDescriptor} from './transit-route-stops';
import {installTransitInteraction,type TransitPoint,type RouteFeature} from './transit-interaction';
import {publicTransitControls,publicTransitModes,type PublicTransitMode,type TransitAvailabilityMap} from './public-transit-controls';
export type TransitGeometryStatus='verified_gtfs_shapes'|'verified_osm_route_relations';
type Locale='zh'|'en'|'de';export type TransitBounds=[number,number,number,number];
export type TransitTile={id:string;path:string;sha256:string;bytes:number;bbox:TransitBounds};
export type TransitModeManifest={status:'available'|'unverified'|'absent_by_official_source';source?:{name:string;url:string;sha256:string;license_url:string};reference_date?:string;routeCoverage?:string;routeCoverage_localized?:Record<Locale,string>;geometry_status?:TransitGeometryStatus;tiles?:TransitTile[];stop_lists_index?:StopDescriptor};
export type PublicTransitManifest={schema_version:1;city:string;modes:Partial<Record<PublicTransitMode,TransitModeManifest>>};
export type TransitMap={getSource(id:string):any;addSource(id:string,source:any):void;removeSource(id:string):void;getLayer(id:string):any;addLayer(layer:any):void;removeLayer(id:string):void;setFilter(id:string,filter:any):void;on(event:string,listener:()=>void):void;off(event:string,listener:()=>void):void;getBounds():{getWest():number;getSouth():number;getEast():number;getNorth():number};queryRenderedFeatures?(box:any,options:{layers:string[]}):readonly {properties?:Record<string,unknown>}[];getContainer?():HTMLElement};
export type PublicTransitOverlayOptions={map:TransitMap;host:HTMLElement;city:string;locale:Locale;fetchBytes:(path:string,signal:AbortSignal,maxBytes:number)=>Promise<Uint8Array>;manifestPath?:string;getBounds?:()=>TransitBounds;onAvailability?:(value:TransitAvailabilityMap)=>void;refreshTimeoutMs?:number;onStatus?:(state:'idle'|'loading'|'error'|'unverified',detail?:string)=>void};
const TILE_LIMIT=32,BYTE_LIMIT=8*1024*1024,TILE_BYTE_LIMIT=4*1024*1024,MANIFEST_LIMIT=1024*1024,CONCURRENCY=4,MAX_FEATURES=20000,MAX_POINTS=200000;
const HASH=/^[a-f0-9]{64}$/,safePath=(s:unknown):s is string=>typeof s==='string'&&s.length<=512&&/^\/safety\/transit\/[A-Za-z0-9_./-]+$/.test(s)&&!s.split('/').some(p=>p==='..'||p==='.'),https=(s:unknown)=>typeof s==='string'&&/^https:\/\//.test(s),bounds=(b:unknown):b is TransitBounds=>Array.isArray(b)&&b.length===4&&b.every(Number.isFinite)&&b[0]>=-180&&b[2]<=180&&b[1]>=-90&&b[3]<=90&&b[0]<=b[2]&&b[1]<=b[3];
export function parsePublicTransitManifest(value:unknown,city:string):PublicTransitManifest{
 const v=value as PublicTransitManifest;if(!v||v.schema_version!==1||v.city!==city||!v.modes||Array.isArray(v.modes)||Object.keys(v.modes).some(m=>!publicTransitModes.includes(m as PublicTransitMode)))throw Error('Invalid public transit manifest');
 for(const entry of Object.values(v.modes)){
  if(!entry||!['available','unverified','absent_by_official_source'].includes(entry.status))throw Error('Invalid mode status');
  if(entry.routeCoverage_localized!==undefined&&!['zh','en','de'].every(lang=>typeof entry.routeCoverage_localized?.[lang as Locale]==='string'&&entry.routeCoverage_localized[lang as Locale].trim().length>0&&entry.routeCoverage_localized[lang as Locale].length<5000))throw Error('Invalid localized route coverage');
  if(entry.source&&(!entry.source.name?.trim()||!https(entry.source.url)||!HASH.test(entry.source.sha256)||!https(entry.source.license_url)))throw Error('Invalid source provenance');
  if(entry.status==='absent_by_official_source'&&(!entry.source||!entry.routeCoverage?.trim()))throw Error('Absence requires official source and scope');
  if(entry.stop_lists_index!==undefined&&(!stopDescriptor(entry.stop_lists_index)||entry.status!=='available'))throw Error('Invalid stop index provenance');
  if(entry.status==='available'){
   if(!entry.source||!['verified_gtfs_shapes','verified_osm_route_relations'].includes(entry.geometry_status??'')||!entry.reference_date?.trim()||!entry.routeCoverage?.trim()||!Array.isArray(entry.tiles)||!entry.tiles.length||entry.tiles.length>32768)throw Error('Unverified geometry cannot be available');
   const ids=new Set();for(const t of entry.tiles){if(!t||typeof t.id!=='string'||!t.id||ids.has(t.id)||!safePath(t.path)||!HASH.test(t.sha256)||!Number.isInteger(t.bytes)||t.bytes<1||t.bytes>TILE_BYTE_LIMIT||!bounds(t.bbox))throw Error('Invalid transit tile');ids.add(t.id);}
  }else if(entry.tiles?.length)throw Error('Unverified/absent mode must not expose tiles');
 }return v;
}
export function intersectsTransitBounds(a:TransitBounds,b:TransitBounds){return a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1];}
export function parsePublicTransitTile(value:unknown,city:string,mode:PublicTransitMode,expectedGeometry?:TransitGeometryStatus){
 const v=value as any;if(!v||v.type!=='FeatureCollection'||v.city!==city||v.mode!==mode||!['verified_gtfs_shapes','verified_osm_route_relations'].includes(v.geometry_source)||(expectedGeometry&&v.geometry_source!==expectedGeometry)||!Array.isArray(v.features)||v.features.length>MAX_FEATURES)throw Error('Invalid transit geometry');let points=0;
 for(const f of v.features){if(!f||f.type!=='Feature'||f.properties?.mode!==mode||typeof f.properties.route_id!=='string'||!f.properties.route_id||(v.geometry_source==='verified_gtfs_shapes'?!f.properties.shape_id:!f.properties.relation_id)||!['LineString','MultiLineString'].includes(f.geometry?.type))throw Error('Only source route shapes are accepted');const lines=f.geometry.type==='LineString'?[f.geometry.coordinates]:f.geometry.coordinates;if(!Array.isArray(lines)||!lines.length)throw Error('Invalid route shape');for(const line of lines){if(!Array.isArray(line)||line.length<2)throw Error('Invalid shape sequence');for(const p of line){if(!Array.isArray(p)||p.length<2||!Number.isFinite(p[0])||!Number.isFinite(p[1])||Math.abs(p[0])>180||Math.abs(p[1])>90||++points>MAX_POINTS)throw Error('Invalid shape point');}}}return v;
}
/** Source line segments intersect the actual viewport; an enclosing bbox alone is insufficient. */
export function routeGeometryIntersectsBounds(features:readonly RouteFeature[],box:TransitBounds):boolean{
 if(!bounds(box))return false;
 const segment=(a:number[],b:number[])=>{let lo=0,hi=1;const dx=b[0]-a[0],dy=b[1]-a[1];for(const [p,q]of [[-dx,a[0]-box[0]],[dx,box[2]-a[0]],[-dy,a[1]-box[1]],[dy,box[3]-a[1]]]){if(p===0){if(q<0)return false;}else{const t=q/p;if(p<0)lo=Math.max(lo,t);else hi=Math.min(hi,t);if(lo>hi)return false;}}return true;};
 for(const f of features){const lines=f.geometry?.type==='LineString'?[f.geometry.coordinates]:f.geometry?.type==='MultiLineString'?f.geometry.coordinates:[];for(const line of lines)for(let i=1;i<line.length;i++)if(segment(line[i-1],line[i]))return true;}return false;
}
const empty=()=>({type:'FeatureCollection',features:[]}),mainModes=new Set<PublicTransitMode>(['metro','tram','bus']),group=(mode:PublicTransitMode)=>mainModes.has(mode)?mode:'extra',sourceId=(g:string)=>'public-transit-'+g,layerId=(g:string)=>'public-transit-'+g+'-lines';
/** City-local, viewport bounded and independent of police months/generations. */
export function installPublicTransitOverlay(options:PublicTransitOverlayOptions){
 const {map,city}=options;let bootstrap=new AbortController();const modeState=new Map<PublicTransitMode,{abort:AbortController;revision:number;pending:boolean;deadline?:number;timer?:ReturnType<typeof setTimeout>}>(),displayedEntry=new Map<PublicTransitMode,TransitModeManifest>(),cache=new Map<string,{data:any;bytes:number}>(),displayed=new Map<PublicTransitMode,any[]>();let manifest:PublicTransitManifest|undefined,selected=new Set<PublicTransitMode>(),destroyed=false,suspended=false,bootstrapRevision=0,cacheBytes=0,active=0,peak=0;const queue:{run:()=>void;signal:AbortSignal}[]=[];
 const timeout=options.refreshTimeoutMs??10000;if(!Number.isInteger(timeout)||timeout<1||timeout>30000)throw Error('Invalid bounded refresh timeout');
 const interaction=installTransitInteraction({map,host:map.getContainer?.()??options.host,locale:options.locale,city,fetchBytes:options.fetchBytes,isRefreshing:mode=>!!modeState.get(mode)?.pending&&!modeState.get(mode)?.abort.signal.aborted&&selected.has(mode)&&manifest?.modes[mode]===displayedEntry.get(mode),isRouteVisible:r=>routeGeometryIntersectsBounds(r.features,getBounds()),loaded:()=>[...displayed].filter(([m])=>selected.has(m)).flatMap(([,f])=>f) as RouteFeature[],manifest:()=>manifest});
 const controls=publicTransitControls(options.host,options.locale,s=>setSelected(s),()=>void load());
 const status=(s:'idle'|'loading'|'error'|'unverified',detail?:string)=>{if(destroyed)return;options.onStatus?.(s,detail);if(s==='loading')controls.loading(detail);else if(s==='error')controls.error(detail);else controls.idle(detail);};
 const setup=()=>{if(destroyed)return;for(const g of ['metro','tram','bus','extra']){if(!map.getSource(sourceId(g)))map.addSource(sourceId(g),{type:'geojson',data:empty()});if(!map.getLayer(layerId(g)))map.addLayer({id:layerId(g),type:'line',source:sourceId(g),paint:{'line-color':g==='metro'?'#427bc5':g==='tram'?'#be5850':g==='bus'?'#4a9668':'#9a80b5','line-width':g==='bus'?1.5:2.2,'line-opacity':.8}});}};
 function render(){if(destroyed)return;setup();for(const g of ['metro','tram','bus','extra']){const features=[...displayed].filter(([m])=>selected.has(m)&&group(m)===g).flatMap(([,f])=>f);map.getSource(sourceId(g))?.setData({type:'FeatureCollection',features});}map.setFilter(layerId('extra'),['in',['get','mode'],['literal',[...selected].filter(m=>!mainModes.has(m))]]);interaction.update();}
 function cancel(mode:PublicTransitMode,retain=false){const old=modeState.get(mode);old?.abort.abort();if(old?.timer)clearTimeout(old.timer);const deadline=retain?(old?.deadline??Date.now()+timeout):undefined;const state={abort:new AbortController(),revision:(old?.revision??0)+1,pending:retain,deadline,timer:undefined as ReturnType<typeof setTimeout>|undefined};modeState.set(mode,state);
  if(!retain){displayed.delete(mode);displayedEntry.delete(mode);return;}
  state.timer=setTimeout(()=>{if(destroyed||modeState.get(mode)!==state||!state.pending)return;state.pending=false;state.abort.abort();displayed.delete(mode);displayedEntry.delete(mode);render();status('error');},Math.max(0,deadline!-Date.now()));
 }
 function settled(mode:PublicTransitMode){const state=modeState.get(mode);if(state){state.pending=false;state.deadline=undefined;if(state.timer)clearTimeout(state.timer);state.timer=undefined;}}
 function remember(key:string,data:any,bytes:number){const old=cache.get(key);if(old){cache.delete(key);cacheBytes-=old.bytes;}while(cache.size>=TILE_LIMIT||cacheBytes+bytes>BYTE_LIMIT){const k=cache.keys().next().value;if(k===undefined)break;const e=cache.get(k)!;cache.delete(k);cacheBytes-=e.bytes;}cache.set(key,{data,bytes});cacheBytes+=bytes;}
 function cached(key:string){const e=cache.get(key);if(e){cache.delete(key);cache.set(key,e);}return e;}
 function pump(){if(destroyed)return;while(active<CONCURRENCY&&queue.length){const task=queue.shift()!;task.run();}}
 function schedule<T>(signal:AbortSignal,fn:()=>Promise<T>):Promise<T>{return new Promise((resolve,reject)=>{let started=false,settled=false;const finish=()=>{if(started){active--;pump();}};const aborted=()=>{if(settled)return;settled=true;if(!started){const i=queue.indexOf(task);if(i>=0)queue.splice(i,1);}reject(new DOMException('Aborted','AbortError'));};const task={signal,run:()=>{if(signal.aborted){aborted();return;}started=true;active++;peak=Math.max(peak,active);fn().then(v=>{if(!settled){settled=true;resolve(v);}},e=>{if(!settled){settled=true;reject(e);}}).finally(()=>{signal.removeEventListener('abort',aborted);finish();});}};if(signal.aborted){aborted();return;}signal.addEventListener('abort',aborted,{once:true});queue.push(task);pump();});}
 async function tile(t:TransitTile,mode:PublicTransitMode,signal:AbortSignal){const key=city+'/'+mode+'/'+t.sha256+'/'+t.path,hit=cached(key);if(hit)return hit.data;return schedule(signal,async()=>{const b=await options.fetchBytes(t.path,signal,Math.min(TILE_BYTE_LIMIT,t.bytes));if(signal.aborted)throw new DOMException('Aborted','AbortError');if(!(b instanceof Uint8Array)||b.byteLength!==t.bytes||b.byteLength>TILE_BYTE_LIMIT)throw Error('Transit tile size mismatch');const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(b).buffer))].map(v=>v.toString(16).padStart(2,'0')).join('');if(signal.aborted)throw new DOMException('Aborted','AbortError');if(digest!==t.sha256)throw Error('Transit tile hash mismatch');const data=parsePublicTransitTile(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(b)),city,mode,manifest?.modes[mode]?.geometry_status);if(signal.aborted)throw new DOMException('Aborted','AbortError');remember(key,data,b.byteLength);return data;});}
 function getBounds(){if(options.getBounds)return options.getBounds();const b=map.getBounds();return[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()] as TransitBounds;}
 function refresh(){if(destroyed||suspended)return;for(const mode of selected)cancel(mode,manifest?.modes[mode]?.status==='available'&&manifest.modes[mode]===displayedEntry.get(mode)&&displayed.has(mode));render();if(!manifest){if(selected.size)status('unverified',({zh:'路线清单仍在加载或尚未核验。',en:'The route list is still loading or is not yet verified.',de:'Der Linienkatalog wird noch geladen oder ist noch nicht geprüft.'})[options.locale]);return;}const box=getBounds();if(!bounds(box)){for(const mode of selected){settled(mode);displayed.delete(mode);displayedEntry.delete(mode);}render();status('error',({zh:'无法读取当前地图范围。请移动地图后重试。',en:'The current map area could not be read. Move the map to retry.',de:'Der aktuelle Kartenausschnitt konnte nicht gelesen werden. Verschieben Sie die Karte, um es erneut zu versuchen.'})[options.locale]);return;}const wanted=new Map<PublicTransitMode,TransitTile[]>(),pools=new Map<PublicTransitMode,TransitTile[]>();let unverified=false;
  for(const mode of selected){const e=manifest.modes[mode];if(e?.status!=='available'){unverified=true;continue;}pools.set(mode,e.tiles!.filter(t=>intersectsTransitBounds(t.bbox,box)).sort((a,b)=>a.id.localeCompare(b.id)));wanted.set(mode,[]);}
  // Total visible request/cache set <=32, allocated round-robin across selected modes.
  let remaining=TILE_LIMIT,remainingBytes=BYTE_LIMIT,skipped=false,more=true;while(remaining&&more){more=false;for(const[mode,pool]of pools){if(!remaining)break;if(pool.length){const next=pool.shift()!;if(next.bytes<=remainingBytes){wanted.get(mode)!.push(next);remaining--;remainingBytes-=next.bytes;}else skipped=true;more=true;}}}
  let pending=wanted.size,failed=false;if(!pending){status(unverified?'unverified':'idle');return;}status('loading');
  for(const[mode,tiles]of wanted){const state=modeState.get(mode)!,rev=state.revision,signal=state.abort.signal;Promise.all(tiles.map(t=>tile(t,mode,signal))).then(data=>{if(destroyed||signal.aborted||modeState.get(mode)?.revision!==rev||!selected.has(mode))return;settled(mode);displayed.set(mode,data.flatMap(d=>d.features));displayedEntry.set(mode,manifest!.modes[mode]!);render();}).catch(()=>{if(!signal.aborted&&!destroyed){failed=true;settled(mode);displayed.delete(mode);displayedEntry.delete(mode);render();}}).finally(()=>{if(destroyed||signal.aborted||modeState.get(mode)?.revision!==rev)return;if(--pending===0)status(failed?'error':unverified?'unverified':'idle',skipped||[...pools.values()].some(p=>p.length)?({zh:'当前可见范围仅载入部分路线。',en:'Only part of the visible route coverage is loaded.',de:'Nur ein Teil der sichtbaren Linienabdeckung ist geladen.'})[options.locale]:undefined);});}
 }
 function setSelected(modes:ReadonlySet<PublicTransitMode>){if(destroyed)return;if([...modes].some(m=>!publicTransitModes.includes(m)))throw Error('Invalid transit mode');for(const mode of selected)if(!modes.has(mode))cancel(mode);selected=new Set(modes);refresh();}
 async function load(){if(destroyed||suspended)return;const bootstrapSignal=bootstrap.signal,ticket=++bootstrapRevision;const p=options.manifestPath??'/safety/transit/index.json';if(!safePath(p))throw Error('Invalid transit manifest path');try{const b=await options.fetchBytes(p,bootstrapSignal,MANIFEST_LIMIT);if(destroyed||suspended||bootstrapSignal.aborted||ticket!==bootstrapRevision)return;if(!(b instanceof Uint8Array)||b.length>MANIFEST_LIMIT)throw Error('Transit manifest exceeds limit');manifest=parsePublicTransitManifest(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(b)),city);const availability:TransitAvailabilityMap={};for(const mode of publicTransitModes){const e=manifest.modes[mode];availability[mode]={status:e?.status??'unverified',source:e?.source?.name,date:e?.reference_date,routeCoverage:e?.routeCoverage_localized?.[options.locale]??e?.routeCoverage};}controls.setAvailable(availability);options.onAvailability?.(availability);refresh();}catch{if(!destroyed&&!suspended&&!bootstrapSignal.aborted&&ticket===bootstrapRevision){if(!manifest)controls.setAvailable({});status('error',({zh:'路线清单未能加载，请重试。已验证的旧路线会保留；加载失败不表示本市没有这些服务。',en:'The route list could not be loaded. Retry to check it again. Previously verified routes are retained; this failure does not indicate a missing service.',de:'Der Linienkatalog konnte nicht geladen werden. Versuchen Sie es erneut. Bereits geprüfte Linien bleiben erhalten; der Ladefehler bedeutet nicht, dass diese Dienste fehlen.'})[options.locale]);}}}
 const move=()=>refresh();map.on('moveend',move);setup();return{load,setSelected,refresh,inspectAt:(point:TransitPoint)=>interaction.inspect(point),inspectStopAt:(point:TransitPoint)=>interaction.inspectStop(point),clearSelection:()=>interaction.clear(),suspend(){if(destroyed||suspended)return;suspended=true;bootstrapRevision++;bootstrap.abort();for(const s of modeState.values()){s.abort.abort();if(s.timer)clearTimeout(s.timer);s.pending=false;}displayed.clear();displayedEntry.clear();render();status('idle');},resume(){if(destroyed||!suspended)return;suspended=false;bootstrap=new AbortController();if(manifest)refresh();else void load();},controls,cacheStats:()=>({tiles:cache.size,bytes:cacheBytes,active,queued:queue.length,peakConcurrency:peak}),destroy(){if(destroyed)return;interaction.destroy();destroyed=true;bootstrap.abort();for(const s of modeState.values()){s.abort.abort();if(s.timer)clearTimeout(s.timer);}queue.length=0;map.off('moveend',move);controls.destroy();cache.clear();cacheBytes=0;displayed.clear();for(const g of ['metro','tram','bus','extra']){if(map.getLayer(layerId(g)))map.removeLayer(layerId(g));if(map.getSource(sourceId(g)))map.removeSource(sourceId(g));}}};
}
