export const publicTransitModes=['metro','tram','bus','s_bahn','rail','ferry'] as const;
export type PublicTransitMode=typeof publicTransitModes[number];
export type TransitAvailability={status:'available'|'unverified'|'absent_by_official_source';source?:string;date?:string;routeCoverage?:string};
export type TransitAvailabilityMap=Partial<Record<PublicTransitMode,TransitAvailability>>;
type Locale='de'|'en'|'zh';
const COPY={zh:{title:'公共交通路线',extra:'其他公共交通',metro:'地铁',tram:'电车',bus:'公交',s_bahn:'S-Bahn 市郊铁路',rail:'其他铁路',ferry:'轮渡',available:'已取得可核验路线',unverified:'尚未取得可核验路线；不表示该城市没有此服务',absent:'官方来源明确该范围没有此服务',loading:'正在加载所选路线…',error:'所选路线加载失败；不表示没有此服务',source:'来源',date:'数据快照日期',coverage:'路线覆盖',idle:'交通路线参考，不代表警情关联；与警情月份和地点筛选分别控制'},en:{title:'Public transport routes',extra:'Other public transport',metro:'Metro',tram:'Tram',bus:'Bus',s_bahn:'S-Bahn suburban rail',rail:'Other rail',ferry:'Ferry',available:'Verifiable routes acquired',unverified:'Verifiable routes not yet acquired; this does not mean the city lacks this service',absent:'Official source confirms no service in this scope',loading:'Loading selected routes…',error:'Selected routes failed to load; this does not mean no service exists',source:'Source',date:'Data snapshot date',coverage:'Route coverage',idle:'Transport route reference, without implying links to police reports; separate from police months and place filters'},de:{title:'Öffentliche Verkehrswege',extra:'Weitere öffentliche Verkehrsmittel',metro:'U-Bahn',tram:'Straßenbahn',bus:'Bus',s_bahn:'S-Bahn',rail:'Weitere Bahn',ferry:'Fähre',available:'Prüfbare Liniengeometrien vorhanden',unverified:'Prüfbare Liniengeometrien noch nicht vorhanden; dies bedeutet nicht, dass diese Verkehrsart in der Stadt fehlt',absent:'Amtliche Quelle bestätigt kein Angebot in diesem Bezugsraum',loading:'Ausgewählte Linien werden geladen…',error:'Ausgewählte Linien konnten nicht geladen werden; dies bedeutet nicht, dass kein Angebot besteht',source:'Quelle',date:'Datenstand',coverage:'Linienabdeckung',idle:'Verkehrslinien als Referenz, ohne Zuordnung zu Polizeimeldungen; unabhängig von Meldungsmonat und Ortsfiltern'}};
export function publicTransitControls(host:HTMLElement,locale:Locale,onChange:(selected:ReadonlySet<PublicTransitMode>)=>void,onRetry?:()=>void){
 const c=COPY[locale],section=document.createElement('section'),heading=document.createElement('h3'),primary=document.createElement('fieldset'),extra=document.createElement('fieldset'),status=document.createElement('p');
 heading.textContent=c.title;section.className='public-transit-controls';primary.setAttribute('aria-label',c.title);const legend=document.createElement('legend');legend.textContent=c.extra;extra.append(legend);status.setAttribute('role','status');status.setAttribute('aria-live','polite');status.textContent=c.idle;section.append(heading,primary,extra,status);host.append(section);const retry=document.createElement('button');retry.type='button';retry.textContent=({zh:'重试加载交通路线',en:'Retry transport routes',de:'Verkehrslinien erneut laden'})[locale];retry.hidden=true;retry.onclick=()=>{retry.hidden=true;onRetry?.();};section.append(retry);
 const inputs=new Map<PublicTransitMode,HTMLInputElement>(),notes=new Map<PublicTransitMode,HTMLElement>();let destroyed=false;
 function selected():ReadonlySet<PublicTransitMode>{return new Set([...inputs].filter(([,input])=>input.checked&&!input.disabled).map(([mode])=>mode));}
 function changed(){if(!destroyed){status.textContent=c.idle;onChange(selected());}}
 for(const mode of publicTransitModes){const wrapper=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input'),note=document.createElement('p');input.type='checkbox';input.value=mode;input.checked=false;input.disabled=false;input.setAttribute('aria-label',c[mode]);label.className='toggle';const swatch=document.createElement('span');swatch.setAttribute('aria-hidden','true');swatch.style.display='inline-block';swatch.style.width='16px';swatch.style.height='0';swatch.style.borderTop='3px solid '+({metro:'#427bc5',tram:'#be5850',bus:'#4a9668',s_bahn:'#9a80b5',rail:'#9a80b5',ferry:'#9a80b5'}[mode]);swatch.style.flexShrink='0';label.append(input,swatch,document.createTextNode(c[mode]));note.textContent=c.unverified;wrapper.append(label,note);(mode==='metro'||mode==='tram'||mode==='bus'?primary:extra).append(wrapper);input.addEventListener('change',changed);inputs.set(mode,input);notes.set(mode,note);}
 return {element:section,get selected(){return selected();},setAvailable(availability:TransitAvailabilityMap){if(destroyed)return;let selectionChanged=false;
  for(const entry of Object.values(availability)){if(!entry||!['available','unverified','absent_by_official_source'].includes(entry.status))throw Error('Invalid transit availability');if(entry.status==='absent_by_official_source'&&(!entry.source?.trim()||!entry.routeCoverage?.trim()))throw Error('Official absence requires source and scope');}
  for(const mode of publicTransitModes){const entry=availability[mode]??{status:'unverified'},input=inputs.get(mode)!,note=notes.get(mode)!;if(!['available','unverified','absent_by_official_source'].includes(entry.status))throw Error('Invalid transit availability');
   const absent=entry.status==='absent_by_official_source';if(absent&&(!entry.source?.trim()||!entry.routeCoverage?.trim()))throw Error('Official absence requires source and scope');
   if(absent&&input.checked){input.checked=false;selectionChanged=true;}input.disabled=absent;
   note.textContent=[entry.status==='available'?c.available:absent?c.absent:c.unverified,entry.source?c.source+': '+entry.source:'',entry.date?c.date+': '+entry.date:'',entry.routeCoverage?c.coverage+': '+entry.routeCoverage:''].filter(Boolean).join(' · ');
  }if(selectionChanged)changed();},loading(detail?:string){retry.hidden=true;if(!destroyed)status.textContent=c.loading+(detail?.trim()?' '+detail.trim():'');},error(detail?:string){retry.hidden=!onRetry;if(!destroyed)status.textContent=c.error+(detail?.trim()?' '+detail.trim():'');},idle(detail?:string){if(!destroyed)status.textContent=c.idle+(detail?.trim()?' '+detail.trim():'');},destroy(){if(destroyed)return;destroyed=true;for(const input of inputs.values())input.removeEventListener('change',changed);section.remove();}};
}
