import {matchesSourceRule} from './reference-registry-matcher';
import type {SourceRule,SourceContext} from './reference-registry-matcher';
import type {Observation,ReferenceMetric,Text} from './reference-fallback';
export interface PackedCanonicalRegistry {schemaVersion:number;pool:unknown[];rules:unknown[][];scope:string;sourceEvidence:unknown;}
export interface CanonicalRule {base:SourceRule;templateHash:string;columnHashes:Readonly<Record<string,string>>;contexts:ReadonlySet<string>;}
export interface CanonicalMatcher {select(context:SourceContext,metric:ReferenceMetric,signal?:AbortSignal):Promise<Observation|undefined>;}
export function canonicalMethodTemplate(s:string):string {
 return s.replace(/\b(numerator|denominator|total|population)\s+(\d+(?:\.\d+)?)\b/gi,(full:string,k:string,_n:string,offset:number,whole:string)=>/^[–+\-/]|^ years|^year|^ aged/.test(whole.slice(offset+full.length))?full:k+' {EXPLANATORY_COUNT}')
 .replace(/(?<![\d/])\d+(?:\.\d+)?\/\d{3,}(?:\.\d+)?(?![\d/])/g,'{EXPLANATORY_RATIO}')
 .replace(/(native Stadtbezirk|native Stadtteil)\s+\d+\s+[^,;]+(?=[,;])/g,'$1 {AREA_IDENTITY}')
 .replace(/(same native area[^:]*: )\d+(?:\.\d+)?/g,'$1{EXPLANATORY_COUNT}');
}
function ordered(value:unknown):unknown {if(Array.isArray(value))return value.map(ordered);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,ordered((value as Record<string,unknown>)[k])]));return value;}
const canonicalJSON=(v:unknown)=>JSON.stringify(ordered(v));
function field(m:unknown,k:string):unknown {let v:any=m;for(const p of k.split('.')){if(!v||typeof v!=='object'||!Object.hasOwn(v,p)||['__proto__','constructor','prototype'].includes(p))return undefined;v=v[p];}return v;}
async function sha256(text:string):Promise<string>{const result=await globalThis.crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(result),v=>v.toString(16).padStart(2,'0')).join('');}
function throwIfAborted(signal?:AbortSignal):void {if(signal?.aborted)throw new DOMException('Canonical selection cancelled','AbortError');}
async function cancellable<T>(promise:Promise<T>,signal?:AbortSignal):Promise<T>{throwIfAborted(signal);if(!signal)return promise;return new Promise((resolve,reject)=>{const abort=()=>{cleanup();reject(new DOMException('Canonical selection cancelled','AbortError'));};const cleanup=()=>signal.removeEventListener('abort',abort);signal.addEventListener('abort',abort,{once:true});promise.then(v=>{cleanup();if(signal.aborted)reject(new DOMException('Canonical selection cancelled','AbortError'));else resolve(v);},e=>{cleanup();reject(e);});});}
export function expandCanonicalBrowser(registry:PackedCanonicalRegistry):CanonicalRule[]{
 if(registry.schemaVersion!==1||registry.scope!=='local'||!Array.isArray(registry.pool)||!Array.isArray(registry.rules)||registry.rules.length>10000)throw new Error('Invalid canonical registry');
 const p=registry.pool,get=(i:unknown):any=>{if(!Number.isInteger(i)||Number(i)<0||Number(i)>=p.length)throw new Error('Invalid pool index');return p[Number(i)];};
 return registry.rules.map((r,index)=>{if(r.length!==7)throw new Error('Invalid canonical row');const equals:Record<string,unknown>={},columnHashes:Record<string,string>={};let templateHash='';for(const pair of r[3]as number[][]){if(pair.length!==2)throw new Error('Invalid equality pair');const key=get(pair[0]),value=get(pair[1]);if(typeof key!=='string'||['__proto__','constructor','prototype'].some(x=>key.split('.').includes(x)))throw new Error('Invalid field');if(key==='_canonicalMethodTemplateSHA256')templateHash=value;else if(key.startsWith('_canonicalMethodColumnSHA256.'))columnHashes[key.slice('_canonicalMethodColumnSHA256.'.length)]=value;else equals[key]=value;}
  if(!/^[0-9a-f]{64}$/.test(templateHash))throw new Error('Invalid method hash');const city=get(r[0]),conceptId=get(r[1]),title=get(r[2])as Text,levels=(r[5]as number[]).map(get),absent=(r[4]as number[]).map(get);if(typeof city!=='string'||typeof conceptId!=='string'||!levels.every(l=>typeof l==='string')||!absent.every(l=>typeof l==='string'))throw new Error('Invalid identity');const contexts=new Set((r[6]as number[][]).map(([l,a])=>city+'|'+get(l)+'|'+get(a)));return {base:{city,scope:'local',conceptId,title,equals,requiredAbsent:absent,levels,sourceEvidence:{registryEvidence:registry.sourceEvidence,canonicalFamilyIndex:index}},templateHash,columnHashes,contexts};
 });
}
interface MethodResult {template:string;columns:Record<string,string>;}
/** Load one city's runtime lazily. Construction performs no metric hashes or citywide data load. */
export function createCanonicalMatcher(registry:PackedCanonicalRegistry,city:string):CanonicalMatcher {
 const rules=expandCanonicalBrowser(registry).filter(r=>r.base.city===city),buckets=new Map<string,CanonicalRule[]>();for(const r of rules){const key=String(r.base.equals.source_sha256);let list=buckets.get(key);if(!list)buckets.set(key,list=[]);list.push(r);}
 // Weak keys never retain detached metric objects or cache whole-city selection results.
 const cache=new WeakMap<ReferenceMetric,Promise<MethodResult>>(),fingerprints=new WeakMap<ReferenceMetric,string>();
 const method=(metric:ReferenceMetric):Promise<MethodResult>=>{const spec=field(metric,'source_interval_repair_spec'),fingerprint=canonicalJSON([metric.definition.en,spec]);let promise=cache.get(metric);if(promise&&fingerprints.get(metric)===fingerprint)return promise;promise=(async()=>{const template=await sha256(canonicalMethodTemplate(metric.definition.en)),columns:Record<string,string>={};if(spec!==undefined)columns.source_interval_repair_spec=await sha256(canonicalJSON(spec));return {template,columns};})();cache.set(metric,promise);fingerprints.set(metric,fingerprint);return promise;};
 return {async select(context,metric,signal){throwIfAborted(signal);if(context.city!==city||context.scope!=='local'||!context.level||!context.nativeAreaId||context.nativeAreaId!==context.scopeId)return undefined;const candidates=(buckets.get(String(field(metric,'source_sha256')))||[]).filter(r=>r.contexts.has(city+'|'+context.level+'|'+context.scopeId)&&matchesSourceRule(r.base,context,metric));if(!candidates.length)return undefined;const requestFingerprint=canonicalJSON([metric.definition.en,field(metric,'source_interval_repair_spec')]);const hash=await cancellable(method(metric),signal);throwIfAborted(signal);if(requestFingerprint!==canonicalJSON([metric.definition.en,field(metric,'source_interval_repair_spec')]))return undefined;const matching=candidates.filter(r=>matchesSourceRule(r.base,context,metric)&&r.templateHash===hash.template&&Object.entries(r.columnHashes).every(([k,v])=>hash.columns[k]===v));if(matching.length!==1)return undefined;const rule=matching[0].base;return {conceptId:rule.conceptId,city,scope:'local',scopeId:context.scopeId,scopeName:context.scopeName,metric,sourceEvidence:JSON.stringify(rule.sourceEvidence),nativeAreaId:context.nativeAreaId};}};
}
