import {policySections,type Locale} from './reading-policy-copy';
type Text=Readonly<Record<Locale,string>>;
export const SUMMARY:Text={"zh": "逐值查看年份、单位、来源和统计范围。同口径先用本分区最新值，缺新值时优先最近本地历史值。点击位置的其他范围参考不代表整个分区；全市、区域及合并范围另行标注，共同值不分摊。口径未核实使用中性标题、紧邻局限和单值图，不转成百分比。已标注的官方换算估计与实测值分开；缺值不填零。图表不衡量个人风险，也不作安全排名。", "en": "Read each value’s year, unit, source and statistical scope. For the same indicator, use the latest local value, then the most recent local historical observation. A reference containing the clicked point need not cover the whole subdivision. Municipality, region and combined scopes are identified; shared values are not apportioned. An unverified method uses a neutral title, adjacent limitations and a single-value chart without percentage conversion. Labelled official conversion estimates remain distinct from direct observations; missing values are not zero. Charts do not measure personal risk or rank safety.", "de": "Bezugsjahr, Einheit, Quelle und Statistikraum gelten für jeden Wert einzeln. Für denselben Indikator hat der neueste lokale Wert Vorrang, danach der jüngste lokale historische Wert. Ein Referenzraum am angeklickten Punkt muss nicht das ganze Teilgebiet abdecken. Gesamtstadt, Region und zusammengefasste Räume werden benannt; gemeinsame Werte werden nicht aufgeteilt. Ungeprüfte Methodik erhält einen neutralen Titel, benachbarte Einschränkungen und ein Einzelwertdiagramm ohne Prozentumrechnung. Gekennzeichnete amtliche Umrechnungsschätzungen bleiben von direkten Beobachtungen getrennt; fehlende Werte sind nicht null. Diagramme messen kein persönliches Risiko und bilden keine Sicherheitsrangliste."};
export const FRANKFURT:Text={"zh": "仅法兰克福：本批2025年联邦选举值使用官方换算到2026年边界并处理邮寄票的估计；项目占比同样是估计比率，不是原始开票结果。德国及欧盟籍成年居民仅作辅助权重，不表示联邦选举投票资格。", "en": "Frankfurt only: this 2025 federal-election batch uses official estimates converted to 2026 boundaries with postal-vote allocation. Project ratios are also estimates, not original vote-count results. German and EU adults provide auxiliary weights, not federal-election voting entitlement.", "de": "Nur Frankfurt: Diese Daten zur Bundestagswahl 2025 sind amtliche, auf Grenzen von 2026 umgerechnete Schätzwerte mit Briefwahlzuordnung. Projektanteile sind ebenfalls Schätzquotienten, keine ursprünglichen Auszählungsergebnisse. Deutsche und EU-Erwachsene dienen als Hilfsgewichte, nicht als Nachweis der Bundestagswahlberechtigung."};
export const BREMEN:Text={"zh": "不来梅市与不来梅州范围不同；州值包含不来梅港，不能当作市值。", "en": "The city of Bremen and the Land Bremen differ in scope. Land values include Bremerhaven and are not city values.", "de": "Die Stadt Bremen und das Land Bremen haben unterschiedliche Gebietsbezüge. Landeswerte umfassen Bremerhaven und sind keine Stadtwerte."};
export const DETAILS:Text={"zh": "指标来源与详细读法", "en": "Indicator sources and detailed reading notes", "de": "Quellen der Indikatoren und ausführliche Lesehinweise"};
/** Existing rule14 remains one section; native details use ordinary details/summary elements. */
export function appendNewDataReadingPolicy(host:HTMLElement,city:string,locale:Locale,sourceBody:string):void {
 const put=(tag:string,text:string,parent:HTMLElement)=>{const e=document.createElement(tag);e.textContent=text;parent.append(e);return e;};
 put('p',SUMMARY[locale],host);
 if(city==='frankfurt')put('p',FRANKFURT[locale],host);
 if(city==='bremen')put('p',BREMEN[locale],host);
 const details=document.createElement('details');put('summary',DETAILS[locale],details);
 // Guarded staging normalizes only the two reviewed obsolete phrases below.
 const replacements:Record<Locale,readonly [string,string][]>={"zh": [["不填零，不用估计值补齐", "不填零，不用未经核实的估计值补齐"], ["优先使用已发布且可匹配的2026年观测，没有合适版本时使用2025年或注明年份的较早数据", "同口径优先本分区最新已核实观测，缺少较新本地值时保留最近本地历史值，再列其他统计范围参考"]], "en": [["rather than zero or an estimate", "rather than zero or an unverified estimate"], ["Published, matching 2026 observations are preferred, otherwise 2025 or explicitly dated older data", "For the same indicator, the latest verified local observation comes first, followed by the most recent local historical value, then references from other statistical scopes"]], "de": [["nicht durch Null oder Schätzwerte ersetzt", "nicht durch Null oder ungeprüfte Schätzwerte ersetzt"], ["Passende veröffentlichte Werte von 2026 werden bevorzugt, sonst 2025 oder ausdrücklich datierte ältere Werte", "Für denselben Indikator haben neueste geprüfte lokale Werte Vorrang, danach die jüngsten lokalen historischen Werte und anschließend Referenzen anderer Statistikräume"]]};
 let body=sourceBody;for(const [old,next] of replacements[locale])body=body.replace(old,next);
 put('p',body,details);
 for(const section of policySections(city==='frankfurt'?'frankfurt':'berlin',locale)){put('h4',section.title,details);put('p',section.body,details);}
 host.append(details);
}
