import type {Observation,Text} from './reference-fallback';
import type {SourceRule} from './reference-registry-matcher';
import {appendMetricVisual} from './metric-visualization';
import type {AreaMetric} from './area-metrics';
import {loadReviewedLimitationView,type SourceContext,type LimitationView} from './reviewed-limitation-view';
import type {Metric,Locale} from './limitation-contract';
import {REMAINING_LIMIT_REFS,REMAINING_LIMIT_TRIGGERS} from './remaining-limit-descriptors';
export type {SourceContext};
export type LimitGateState={status:'regular'}|{status:'pending'|'withheld'}|{status:'limited';view:LimitationView};
export interface QualifiedLimitedReference {observation:Observation;rule:SourceRule;}
export interface RemainingLimitationGate {needs:(context:SourceContext,metric:Metric)=>boolean;ensure:(context:SourceContext,metric:Metric,signal:AbortSignal)=>Promise<void>;peek:(context:SourceContext,metric:Metric)=>LimitGateState;qualifiedReference:(context:SourceContext,metric:Metric)=>QualifiedLimitedReference|undefined;render:(host:HTMLElement,context:SourceContext,metric:Metric,locale:Locale,format:(metric:Metric,locale:Locale)=>string,visualScope?:'native'|'context')=>LimitGateState;cancel:()=>void;destroy:()=>void;}
const COPY={zh:{pending:'已知来源数值的限制正在核对，核实前暂不显示；这不表示无公布。',withheld:'已知来源数值尚未通过完整限制与来源分区核对，暂不显示；这不表示无公布。'},en:{pending:'Limitations of a known source value are being checked; the value is withheld until verified. This does not establish non-publication.',withheld:'A known source value has not passed limitation and source-area checks and is withheld. This does not establish non-publication.'},de:{pending:'Die Einschränkungen eines bekannten Quellenwertes werden geprüft; bis dahin bleibt der Wert verborgen. Das belegt keine Nichtveröffentlichung.',withheld:'Ein bekannter Quellenwert hat Einschränkungs- und Quellgebietsprüfung nicht bestanden und bleibt verborgen. Das belegt keine Nichtveröffentlichung.'}};
/** Selected detail only, two small city packets and one lazy proof; no raw/cohort mutation. */
export function createRemainingLimitationGate(fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>):RemainingLimitationGate{
 let destroyed=false,epoch=0,proofAbort=new AbortController(),states=new Map<string,WeakMap<Metric,LimitGateState>>(),pending=new Map<string,WeakMap<Metric,Promise<void>>>();const apis=new Map<string,Awaited<ReturnType<typeof loadReviewedLimitationView>>>(),loading=new Map<string,Promise<Awaited<ReturnType<typeof loadReviewedLimitationView>>>>(),loadSignals=new Map<string,AbortSignal>();
 const needs=(c:SourceContext,m:Metric)=>!destroyed&&REMAINING_LIMIT_TRIGGERS.some(t=>t.city===c.city&&t.sourceSha256===m.source_sha256&&t.labelEn===m.label.en);
 const key=(c:SourceContext)=>JSON.stringify([c.city,c.level,c.nativeAreaId]);
 const set=(c:SourceContext,m:Metric,v:LimitGateState)=>{const k=key(c);let map=states.get(k);if(!map){map=new WeakMap();states.set(k,map);while(states.size>8)states.delete(states.keys().next().value!)}map.set(m,v);};
 async function load(city:string,signal:AbortSignal){const cached=apis.get(city);if(cached)return cached;let promise=loading.get(city);if(loadSignals.get(city)?.aborted){loading.delete(city);loadSignals.delete(city);promise=undefined;}if(!promise){promise=(async()=>{const ref=REMAINING_LIMIT_REFS[city as keyof typeof REMAINING_LIMIT_REFS];if(!ref)throw Error('Limited city unsupported');const bytes=await fetchBytes(ref.path,signal);signal.throwIfAborted();if(bytes.byteLength!==ref.bytes||bytes.byteLength>400000)throw Error('Limited packet byte bound');const api=await loadReviewedLimitationView(new TextDecoder('utf-8',{fatal:true}).decode(bytes),ref.sha256,async path=>{const bytes=await fetchBytes(path,proofAbort.signal);if(bytes.byteLength>400000)throw Error('Limit proof byte bound');return new TextDecoder('utf-8',{fatal:true}).decode(bytes)});signal.throwIfAborted();if(destroyed)throw Error('Limited gate destroyed');apis.set(city,api);return api;})();loading.set(city,promise);loadSignals.set(city,signal);const same=promise;void promise.finally(()=>{if(loading.get(city)===same){loading.delete(city);loadSignals.delete(city);}}).catch(()=>{});}return promise;}
 const peek=(c:SourceContext,m:Metric):LimitGateState=>!needs(c,m)?{status:'regular'}:states.get(key(c))?.get(m)??{status:'pending'};
 const cancel=()=>{epoch++;proofAbort.abort();proofAbort=new AbortController();pending=new Map();};
 return {needs,peek,qualifiedReference(context,metric){const state=peek(context,metric);if(destroyed||state.status!=='limited')return undefined;const approved=apis.get(context.city)?.qualifiedReference(state.view);if(!approved)return undefined;const original=approved.observation;return {rule:approved.rule,observation:{...original,metric:original.metric as Observation['metric'],scopeName:(context.scopeName??original.scopeName) as Text,sourceNativeLevel:context.level,sourceQualifiedLimitation:original.visibleLimitations[0] as Text,nativeAreaId:context.nativeAreaId}};},async ensure(context,metric,signal){if(!needs(context,metric))return;signal.throwIfAborted();const existing=peek(context,metric);if(existing.status==='limited'||existing.status==='withheld')return;const k=key(context);let map=pending.get(k);if(!map){map=new WeakMap();pending.set(k,map);while(pending.size>8)pending.delete(pending.keys().next().value!)}let operation=map.get(metric);if(!operation){const ticket=epoch;operation=(async()=>{try{const api=await load(context.city,signal);signal.throwIfAborted();const qualified=await api.qualify(context,metric,signal);signal.throwIfAborted();if(destroyed||ticket!==epoch)return;set(context,metric,qualified.status==='limited'?qualified:{status:'withheld'});}catch{if(!destroyed&&ticket===epoch&&!signal.aborted)set(context,metric,{status:'withheld'});}})();map.set(metric,operation);}await operation;signal.throwIfAborted();},render(host,context,metric,locale,format,visualScope='context'){const state=peek(context,metric);if(state.status==='regular')return state;if(state.status==='limited'){const api=apis.get(context.city);if(api?.render(host,state.view,locale,format,(detached,original,l,scope)=>appendMetricVisual(detached,original as unknown as AreaMetric,l,{scope}),visualScope).status==='rendered')return state;}const note=document.createElement('p');note.className='remaining-limit-withheld';note.textContent=COPY[locale][state.status==='pending'?'pending':'withheld'];host.append(note);return {status:state.status==='pending'?'pending':'withheld'};},cancel,destroy(){cancel();destroyed=true;states.clear();for(const api of apis.values())api.destroy();apis.clear();}};
}
