import {referenceObservation,type SourceRule} from './reference-registry-matcher';
import type {Observation,Text} from './reference-fallback';
export interface SharedFileRef {path:string;sha256:string;bytes:number;}
export interface SharedSelection {city:string;nativeLevel:string;selectedNativeAreaId:string;currentGeometrySha256:string;}
export interface ReviewedSharedDescriptor {city:string;scopeId:string;nativeLevel:string;memberAreaIds:readonly string[];geometrySha256:string;metricsRef:SharedFileRef;registryRef:SharedFileRef;containerLevel:string;areaNameField:'name'|'scopeName';membershipEvidenceSha256:string;metrics:readonly {metricId:string;conceptId:string;value:number;unit:string;year:number;referenceDate?:string;sourceSha256:string;metricSha256:string;ruleSha256:string;}[];badge:Text;note:Text;}
export interface SharedReferences {observations:Observation[];rules:SourceRule[];descriptor:ReviewedSharedDescriptor;}
export class SharedGroupError extends Error {readonly code:string;constructor(code:string){super(`Shared source reference unavailable: ${code}`);this.code=code;this.name='SharedGroupError';}}
function fail(code:string):never{throw new SharedGroupError(code);}
const LIMIT=8*1024*1024;
const obj=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function localized(v:unknown):v is Text{return obj(v)&&['zh','en','de'].every(l=>typeof v[l]==='string'&&v[l].trim()&&v[l].length<5000);}
/** Canonical ordering is only for integrity comparison; original data objects are never rewritten. */
export function canonicalSharedJSON(value:unknown):string {let nodes=0;const walk=(v:unknown,depth:number):unknown=>{if(++nodes>200000||depth>32)fail('structure-limit');if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isFinite(v))fail('number');return v;}if(Array.isArray(v))return v.map(x=>walk(x,depth+1));if(obj(v)){const out:Record<string,unknown>={};for(const key of Object.keys(v).sort()){if(['__proto__','prototype','constructor'].includes(key))fail('key');out[key]=walk(v[key],depth+1);}return out;}return fail('json-value');};return JSON.stringify(walk(value,0));}
async function digest(bytes:Uint8Array){if(bytes.byteLength>LIMIT)fail('byte-limit');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),v=>v.toString(16).padStart(2,'0')).join('');}
export async function sharedObjectHash(v:unknown){return digest(new TextEncoder().encode(canonicalSharedJSON(v)));}
function gate(d:ReviewedSharedDescriptor,s:SharedSelection){if(s.city!==d.city)fail('city');if(s.nativeLevel!==d.nativeLevel)fail('native-level');if(s.currentGeometrySha256!==d.geometrySha256)fail('geometry-version');if(d.memberAreaIds.length<2||d.memberAreaIds.length>128||new Set(d.memberAreaIds).size!==d.memberAreaIds.length||!d.memberAreaIds.every(x=>typeof x==='string'&&x)||!d.metrics.length||d.metrics.length>128)fail('descriptor');}
/** Descriptor must be independently reviewed and supplied by the caller, never inferred from raw inputs. */
export async function parseReviewedSharedGroup(metricsRaw:unknown,registryRaw:unknown,d:ReviewedSharedDescriptor,s:SharedSelection):Promise<SharedReferences>{
 gate(d,s);if(!obj(metricsRaw)||metricsRaw.city!==d.city||metricsRaw.level!==d.containerLevel||!Array.isArray(metricsRaw.areas)||metricsRaw.areas.length!==1||metricsRaw.native_geography_inheritance===true)fail('container');const area=metricsRaw.areas[0];
 if(!obj(area)||area.id!==d.scopeId||!same(area.memberAreaIds,d.memberAreaIds)||!localized(area[d.areaNameField])||area.geometry!==undefined||area.geometry_available===true||!Array.isArray(area.metrics)||area.metrics.length!==d.metrics.length)fail('shared-scope');
 if(area.memberNativeLevel!==undefined&&area.memberNativeLevel!==d.nativeLevel)fail('member-level');if(!obj(area.membershipEvidence)||await sharedObjectHash(area.membershipEvidence)!==d.membershipEvidenceSha256)fail('membership-evidence');
 if(!obj(registryRaw)||!Array.isArray(registryRaw.rules)||registryRaw.rules.length!==d.metrics.length)fail('registry');const rules=registryRaw.rules as SourceRule[],seen=new Set<string>();
 for(const metric of area.metrics){if(!obj(metric)||typeof metric.metric_id!=='string'||seen.has(metric.metric_id))fail('metric');seen.add(metric.metric_id);const spec=d.metrics.find(m=>m.metricId===metric.metric_id);
  if(!spec||metric.value!==spec.value||metric.unit!==spec.unit||metric.year!==spec.year||metric.reference_date!==spec.referenceDate||metric.source_sha256!==spec.sourceSha256||!localized(metric.label)||!localized(metric.definition)||metric.native_geography_inheritance===true||await sharedObjectHash(metric)!==spec.metricSha256)fail('source-metric');
  const rule=rules.filter(r=>r?.conceptId===spec.conceptId);if(rule.length!==1||rule[0].city!==d.city||rule[0].scope!=='merged'||rule[0].scopeId!==d.scopeId||!localized(rule[0].title)||!rule[0].sourceEvidence||await sharedObjectHash(rule[0])!==spec.ruleSha256)fail('source-rule');
 }
 if(!d.memberAreaIds.includes(s.selectedNativeAreaId))return {observations:[],rules:[],descriptor:d};
 const membershipEvidence=JSON.stringify(area.membershipEvidence),observations:Observation[]=[];
 for(const metric of area.metrics){const o=referenceObservation({city:d.city,scope:'merged',scopeId:d.scopeId,scopeName:area[d.areaNameField],level:d.nativeLevel},metric,rules);if(!o)fail('source-match');observations.push({...o,memberAreaIds:area.memberAreaIds,membershipEvidence});}
 return {observations,rules,descriptor:d};
}
async function loadJSON(ref:SharedFileRef,fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>,signal:AbortSignal){if(signal.aborted)fail('aborted');if(!Number.isSafeInteger(ref.bytes)||ref.bytes<1||ref.bytes>LIMIT||!/^[a-f0-9]{64}$/.test(ref.sha256)||!/^\/safety\/geography\/(?:reference-merged|merged-references)\/[a-zA-Z0-9_.-]+\.json$/.test(ref.path))fail('reference');const bytes=await fetchBytes(ref.path,signal);if(signal.aborted)fail('aborted');if(bytes.byteLength!==ref.bytes||await digest(bytes)!==ref.sha256)fail('sha-or-size');if(signal.aborted)fail('aborted');try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{return fail('json');}}
export async function loadReviewedSharedGroup(options:{descriptor:ReviewedSharedDescriptor;selection:SharedSelection;fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>;signal:AbortSignal}):Promise<SharedReferences>{const {descriptor:d,selection:s}=options;gate(d,s);if(!d.memberAreaIds.includes(s.selectedNativeAreaId))return {observations:[],rules:[],descriptor:d};const metrics=await loadJSON(d.metricsRef,options.fetchBytes,options.signal),registry=await loadJSON(d.registryRef,options.fetchBytes,options.signal);const result=await parseReviewedSharedGroup(metrics,registry,d,s);if(options.signal.aborted)fail('aborted');return result;}
