import {createLimitationContract,sha256Text,type Metric,type Locale,type QualifiedObservation,type Text} from './limitation-contract';
import {matchesSourceRule,type SourceRule} from './reference-registry-matcher';
export interface SourceContext {city:string;level:string;nativeAreaId:string;scopeName?:Text;}
export interface LimitationView {readonly metric:Metric;readonly sourceContext:Readonly<SourceContext>;readonly conceptId:string;readonly visibleLimitations:readonly Text[];}
export type LimitResult={status:'not-target'}|{status:'withheld';knownValueNotUnpublished:true;reason:string}|{status:'limited';view:LimitationView};
type Entry={rule:SourceRule;members:{nativeAreaId:string;level:string;metricSHA256:string;value:number|string;year:number}[];};
function canonical(value:any):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value)}
const withheld=(reason:string):LimitResult=>({status:'withheld',knownValueNotUnpublished:true,reason});
/** packetSHA must come from the independently accepted owner descriptor, not the fetched packet. */
export async function loadReviewedLimitationView(packetText:string,packetSHA:string,loadSidecar:(path:string)=>Promise<string>){
 if(!/^[a-f0-9]{64}$/.test(packetSHA)||new TextEncoder().encode(packetText).byteLength>400000||await sha256Text(packetText)!==packetSHA)throw Error('Limited view packet unavailable');const packet=JSON.parse(packetText);if(packet?.schemaVersion!==1||packet.format!=='civiflux-reviewed-limitations-v1'||!['dresden','munich'].includes(packet.city)||!Array.isArray(packet.entries)||packet.entries.length<1||packet.entries.length>11||!Array.isArray(packet.sidecars)||packet.sidecars.length>1)throw Error('Limited view envelope');
 const originalEntries=packet.entries as Entry[];const ruleText=JSON.stringify({rules:originalEntries.map(e=>e.rule)}),contract=createLimitationContract({maxCachedSidecars:4,loadSidecar:async path=>{const ref=packet.sidecars.find((r:any)=>r.path===path);if(!ref||!/^\/safety\/geography\/reference-limits\/[a-zA-Z0-9_.-]+\.json$/.test(path)||ref.bytes>400000||!/^[a-f0-9]{64}$/.test(ref.sha256))throw Error('Unapproved limitation sidecar');const text=await loadSidecar(path);if(new TextEncoder().encode(text).byteLength!==ref.bytes||await sha256Text(text)!==ref.sha256)throw Error('Limitation sidecar mismatch');return text;}}),trusted=await contract.loadVerifiedRules(ruleText,await sha256Text(ruleText),packet.city);const entries=originalEntries.map((e,i)=>({...e,rule:trusted[i]}));let destroyed=false;const views=new WeakMap<LimitationView,{observation:QualifiedObservation;stamp:string;rule:SourceRule}>();
 for(const e of entries){if(e.rule.scope!=='local'||e.rule.city!==packet.city||e.rule.requireVisibleLimitation!==true||!Array.isArray(e.members)||!e.members.length||e.members.length>356||e.members.some(m=>!e.rule.levels.includes(m.level)||typeof m.nativeAreaId!=='string'||!m.nativeAreaId||!/^[a-f0-9]{64}$/.test(m.metricSHA256)))throw Error('Limited view source binding');}
 const candidates=(context:SourceContext,metric:Metric)=>entries.filter(e=>e.rule.city===context.city&&e.rule.equals.source_sha256===metric.source_sha256&&e.rule.equals['label.en']===metric.label.en);
 return {needs(context:SourceContext,metric:Metric){return !destroyed&&candidates(context,metric).length>0;},async qualify(context:SourceContext,metric:Metric,signal?:AbortSignal):Promise<LimitResult>{if(destroyed)return withheld('destroyed');signal?.throwIfAborted();const target=candidates(context,metric);if(!target.length)return {status:'not-target'};if(target.length!==1)return withheld('ambiguous-limited-source');const e=target[0],source={city:context.city,scope:'local' as const,scopeId:context.nativeAreaId,scopeName:context.scopeName??{zh:context.nativeAreaId,en:context.nativeAreaId,de:context.nativeAreaId},level:context.level,nativeAreaId:context.nativeAreaId};if(!matchesSourceRule(e.rule as unknown as SourceRule,source,metric))return withheld('source-method-mismatch');const digest=await sha256Text(canonical(metric));signal?.throwIfAborted();const member=e.members.find(m=>m.nativeAreaId===context.nativeAreaId&&m.level===context.level&&m.metricSHA256===digest&&m.value===metric.value&&m.year===metric.year);if(!member)return withheld('source-record-mismatch');const result=await contract.qualify(e.rule,{...source,conceptId:e.rule.conceptId,metric,sourceEvidence:JSON.stringify(e.rule.sourceEvidence)},context.level);signal?.throwIfAborted();if(destroyed)return withheld('destroyed');if(result.status!=='qualified')return result;const view=Object.freeze({metric,sourceContext:Object.freeze({...context}),conceptId:e.rule.conceptId,visibleLimitations:result.observation.visibleLimitations});views.set(view,{observation:result.observation,stamp:JSON.stringify(metric),rule:e.rule as unknown as SourceRule});return {status:'limited',view};},qualifiedReference(view:LimitationView){const binding=views.get(view);if(destroyed||!binding||binding.stamp!==JSON.stringify(view.metric))return undefined;return {rule:binding.rule,observation:binding.observation};},render(host:HTMLElement,view:LimitationView,locale:Locale,format:(metric:Metric,locale:Locale)=>string,appendSingleVisual:(host:HTMLElement,metric:Metric,locale:Locale,scope:'native'|'context')=>void,visualScope:'native'|'context'='context'):{status:'rendered'|'withheld';reason?:string}{const binding=views.get(view);if(destroyed||!binding||binding.stamp!==JSON.stringify(view.metric))return {status:'withheld',reason:'stale-or-unqualified-source-view'};return contract.render(host,binding.observation,locale,(detached,o)=>{const line=document.createElement('p');line.textContent=o.metric.label[locale]+': '+format(o.metric,locale);detached.append(line);if(typeof o.metric.value==='number'){if(!Number.isFinite(o.metric.value)||!appendSingleVisual)return false;appendSingleVisual(detached,o.metric,locale,visualScope);}const link=document.createElement('a');link.textContent=o.metric.source_name;link.href=o.metric.source_url;link.target='_blank';link.rel='noopener noreferrer';detached.append(link);return true;});},destroy(){destroyed=true;},cacheInfo:contract.cacheInfo};
}
