import {referenceObservation,type SourceRule} from './reference-registry-matcher';
import type {Observation,Text} from './reference-fallback';
interface Ref {path:string;sha256:string;bytes:number;}
interface Selection {city:string;nativeLevel:string;nativeAreaId:string;geometrySha256:string;}
export interface SharedElectionResult {observations:Observation[];rules:SourceRule[];scopeCaption?:Text;methodNote?:Text;}
const EMPTY:SharedElectionResult={observations:[],rules:[]};
const NOTE:Text={zh:'德国及欧盟籍成年登记居民仅为官方跨边界换算的辅助权重，不代表2025联邦选举的法定投票资格。分母沿用工作簿BTW2025转算wahlb估计；这是官方转换来源的估计比率，不是原始开票投票率。年份2025；2026为边界换算基准；邮寄票按Sperrvermerk选民权重分配，不另行分摊。',en:'Registered German and EU adults are only the auxiliary weighting base for official cross-boundary conversion, not legal voting entitlement in the2025federal election. The denominator remains the workbook’s converted BTW2025 wahlb estimate; these are estimated ratios, not original poll-count turnout. Observation2025, boundary basis2026; postal allocation uses Sperrvermerk weights, with no project redistribution.',de:'Gemeldete deutsche und EU-Erwachsene sind nur Hilfsgewichtungsbasis der amtlichen grenzübergreifenden Umrechnung, keine Aussage zur gesetzlichen Wahlberechtigung2025. Nenner bleibt der umgerechnete BTW2025-wahlb-Schätzwert; geschätzte Quotienten, keine ursprüngliche Auszählungsbeteiligung. Beobachtung2025, Grenzbasis2026; Briefwahl nach Sperrvermerkgewichten, keine zusätzliche Projektverteilung.'};
async function signed(ref:Ref,fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>,signal:AbortSignal,bound:number){if(!/^[a-f0-9]{64}$/.test(ref.sha256)||!Number.isSafeInteger(ref.bytes)||ref.bytes<1||ref.bytes>bound||!/^\/safety\/geography\/reference-election\/frankfurt\/[a-f0-9]{64}(?:-manifest)?\.json$/.test(ref.path))throw Error('Shared election reference invalid');signal.throwIfAborted();const bytes=await fetchBytes(ref.path,signal);signal.throwIfAborted();if(bytes.byteLength!==ref.bytes)throw Error('Shared election bytes invalid');const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),b=>b.toString(16).padStart(2,'0')).join('');if(sha!==ref.sha256)throw Error('Shared election hash invalid');signal.throwIfAborted();return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
/** City+native-level+ID gate precedes the group read; no numeric-ID or point membership inference. */
export function createSharedElectionLoader(options:{manifest:Ref;fetchBytes:(path:string,signal:AbortSignal)=>Promise<Uint8Array>}){
 let manifest:any;const groups=new Map<string,{value:any;bytes:number}>();let bytes=0;
 return {async load(selection:Selection,signal:AbortSignal):Promise<SharedElectionResult>{if(selection.city!=='frankfurt'||!['level1','level2'].includes(selection.nativeLevel))return EMPTY;signal.throwIfAborted();
  if(!manifest){const loaded=await signed(options.manifest,options.fetchBytes,signal,1024*1024);if(loaded.schema_version!==1||loaded.city!=='frankfurt'||!loaded.groups||Object.keys(loaded.groups).length!==7||!loaded.members||!loaded.geometry_sha256)throw Error('Shared election manifest invalid');manifest=loaded;}
  if(manifest.geometry_sha256[selection.nativeLevel]!==selection.geometrySha256)throw Error('Shared election geometry differs');const key='frankfurt/'+selection.nativeLevel+'/'+selection.nativeAreaId,scopeId=manifest.members[key];if(!scopeId)return EMPTY;const ref=manifest.groups[scopeId];if(ref?.native_level!==selection.nativeLevel||!Array.isArray(ref.member_ids)||!ref.member_ids.includes(selection.nativeAreaId))throw Error('Shared election selected membership invalid');
  let group=groups.get(scopeId)?.value;if(!group){group=await signed(ref,options.fetchBytes,signal,8*1024*1024);if(ref.bytes<=1024*1024){while(groups.size>=2||bytes+ref.bytes>1024*1024){const first=groups.keys().next().value;if(!first)break;bytes-=groups.get(first)!.bytes;groups.delete(first);}groups.set(scopeId,{value:group,bytes:ref.bytes});bytes+=ref.bytes;}}
  signal.throwIfAborted();const a=group.scope;if(group.city!=='frankfurt'||group.native_level!==selection.nativeLevel||group.geometry_sha256!==selection.geometrySha256||a?.id!==scopeId||a.memberNativeLevel!==selection.nativeLevel||JSON.stringify(a.memberAreaIds)!==JSON.stringify(ref.member_ids)||!a.memberAreaIds.includes(selection.nativeAreaId)||!Array.isArray(a.metrics)||a.metrics.length!==15||!Array.isArray(group.rules)||group.rules.length!==15||typeof group.membershipEvidence!=='string'||!group.membershipEvidence.trim())throw Error('Shared election group invalid');
  const rules=group.rules as SourceRule[],observations:Observation[]=[],keys=new Set<string>();for(const metric of a.metrics){const o=referenceObservation({city:'frankfurt',scope:'merged',scopeId,scopeName:a.name,level:selection.nativeLevel},metric,rules);if(!o||keys.has(o.conceptId)||metric.year!==2025||metric.reference_date!=='2025'||metric.source_official_derived_estimate!==true||metric.source_geometry_basis_year!==2026)throw Error('Shared election source qualification failed');keys.add(o.conceptId);observations.push({...o,memberAreaIds:a.memberAreaIds,membershipEvidence:group.membershipEvidence});}
  return {observations,rules,scopeCaption:{zh:'官方转换估计共同统计组 · '+selection.nativeLevel+' · '+a.name.zh+'；不是成员分区单独实测',en:'Official-converted estimate shared scope · '+selection.nativeLevel+' · '+a.name.en+'; not an individual member measurement',de:'Gemeinsamer amtlich umgerechneter Schätzraum · '+selection.nativeLevel+' · '+a.name.de+'; kein Einzelgebiets-Messwert'},methodNote:NOTE};
 },destroy(){manifest=undefined;groups.clear();bytes=0;},get cacheStats(){return {groups:groups.size,bytes};}};
}
/** Source-exact method copy for native103/44 rows; original labels/definitions/comparison keys stay intact. */
export function appendOfficialElectionMethodNote(host:HTMLElement,metric:unknown,locale:'zh'|'en'|'de'){const m=metric as any;if(m?.source_sha256!=='da47196b0f365b0f054e90a8fd7f9017403ae35c077a884053657370cc9efe00'||m.source_method!=='same_source_ratio_of_official_atlas_rebased_and_postally_allocated_cells'||m.source_weight_date!=='2025-06-30'||m.year!==2025||m.reference_date!=='2025'||m.source_official_derived_estimate!==true)return;const p=document.createElement('p');p.className='official-election-estimate-note';p.textContent=NOTE[locale];host.append(p);}
