import {officialPoliceScopes} from './area-metrics';
import {referenceObservation,type SourceRule} from './reference-registry-matcher';
import type {Observation,ReferenceMetric,Text} from './reference-fallback';
import {loadHannoverRegionalReferences,regionalReferenceCopy,type RegionalSelection} from './hannover-regional-references';
export interface FrozenReferenceAsset {path:string;sha256:string;bytes:number;}
export interface BroaderReferences {observations:Observation[];rules:SourceRule[];caption:Text;limitation:Text;sourceKind:'regional'|'police';}
export interface BroaderReferenceOptions {selection:RegionalSelection;signal:AbortSignal;fetchBytes:(path:string,signal:AbortSignal,policy?:'no-store')=>Promise<Uint8Array>;}
export const COLOGNE_BROADER_REFS={metrics:{path:'/safety/geography/official-crime-scope-metrics.json',sha256:'4c1516a40a23ec79b1339c6cb74ad6f41fab8621d8b877bd1529bcc0519260a4',bytes:53217},rules:{path:'/safety/geography/reference-regional/cologne-pp2025-rules.json',sha256:'5da7dc5d0067900cdd4588bebe9e9cc7129b0bd39394af9ef15da39a7cac3c5e',bytes:12676},membership:{path:'/safety/geography/reference-regional/cologne-pp-membership.json',sha256:'c9d7ff147a8036d34e4566c73677b449a8b42eb562f14956b6fe416774253f95',bytes:20481},descriptors:{path:'/safety/geography/reference-regional/cologne-pp2025-descriptors.json',sha256:'25553f83e806b4a8cb1bfb0b71479ae768358bfd6794ba9b3ef781b7dd935281',bytes:25108}} as const;
const PP='police/cologne/pp',SOURCE_SHA='be7f5a8f9b3a35507f8240c0370b0eae64a7b60cd9121f9e6be125b931dfacce',PBF='531f35a9fdc523d266fe733f0a96f2b9004996b708765f47437228c374861a04',CITY_BOUNDARY='032a27f18a7cf41e7de08ad28e4b27c41e6f2246347bf3bb409b21203d9a8c56',SOURCE_URL='https://koeln.polizei.nrw/sites/default/files/2026-03/PKS_Jahresbericht_2025.pdf';
const LEVELS:Record<string,{sha256:string;count:number}>={level1:{sha256:'3ef4d9f569f1da8aef6cc91a1c1a151fe7eec67486e869c3ce93f618ffcb5e12',count:86},level2:{sha256:'dbd22e5ee61e19863a7ec8b94ceb8d6bb6fdc4b2855e4e75ab015a4acf10174b',count:9}};
export class BroaderReferenceError extends Error {readonly code:string;constructor(code:string){super('Broader reference unavailable: '+code);this.code=code;this.name='BroaderReferenceError';}}
function fail(code:string):never{throw new BroaderReferenceError(code)}
function text(value:any):value is Text{return value&&['zh','en','de'].every(k=>typeof value[k]==='string'&&value[k].trim())}
function same(a:unknown,b:unknown){return JSON.stringify(a)===JSON.stringify(b)}
async function digest(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),b=>b.toString(16).padStart(2,'0')).join('')}
function canonical(value:any):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value)}
export async function readFrozenReferenceAsset(ref:FrozenReferenceAsset,options:BroaderReferenceOptions,policy?:'no-store'):Promise<any>{
 if(ref.bytes<1||ref.bytes>8*1024*1024||!/^\/safety\/geography\/(?:reference-regional\/)?[a-zA-Z0-9_.-]+\.json$/.test(ref.path)||!/^[a-f0-9]{64}$/.test(ref.sha256))fail('asset-ref');options.signal.throwIfAborted();const bytes=await options.fetchBytes(ref.path,options.signal,policy);options.signal.throwIfAborted();if(bytes.byteLength!==ref.bytes||bytes.byteLength>8*1024*1024)fail('byte-limit');if(await digest(bytes)!==ref.sha256)fail('asset-sha');options.signal.throwIfAborted();return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));
}
/** Authenticated-source parser. Source reviewed complete polygon membership replaces point inference. */
export async function parseCologneBroaderReferences(metricsRaw:any,rulesRaw:any,membership:any,descriptorsRaw:any,selection:RegionalSelection):Promise<BroaderReferences>{
 const expected=LEVELS[selection.nativeLevel];if(selection.city!=='cologne'||!Object.hasOwn(LEVELS,selection.nativeLevel)||selection.currentGeometrySha256!==expected?.sha256)fail('selection');
 if(membership?.status!=='source-and-whole-city-geojoin-verified'||membership.policeSourceURL!==SOURCE_URL||membership.policeSourceSHA256!==SOURCE_SHA||!same(membership.policeMembershipEvidencePages,[7,10,80,86])||membership.sourceCityIdentity?.osmRelation!=='osm/relation/62578'||membership.sourceCityIdentity?.officialMunicipalCode!=='05315000'||membership.sourceCityIdentity?.sourcePbfSHA256!==PBF||membership.municipalBoundarySHA256!==CITY_BOUNDARY||membership.samePbfLayerSources!==true||membership.noPIAggregation!==true||membership.noPPPolygonFabricated!==true||membership.noNativeStatisticInheritance!==true||!Array.isArray(membership.members)||membership.members.length!==95||!Array.isArray(membership.geometryChecks)||membership.geometryChecks.length!==2)fail('membership-envelope');
 for(const [level,binding] of Object.entries(LEVELS)){const matches=membership.geometryChecks.filter((g:any)=>g.level===level);if(matches.length!==1||matches[0].sha256!==binding.sha256||matches[0].features!==binding.count||matches[0].sourcePbfSHA256!==PBF)fail('native-layer-binding')}
 const all=new Set<string>(),levelMembers:string[]=[];const counts:Record<string,number>={level1:0,level2:0};for(const member of membership.members){if(typeof member?.areaId!=='string'||all.has(member.areaId)||!Object.hasOwn(LEVELS,member.level)||member.wholePolygonInsideCologneCity!==true||member.outsideAreaNativeDegreesSquared!==0)fail('native-membership');all.add(member.areaId);counts[member.level]++;if(member.level===selection.nativeLevel)levelMembers.push(member.areaId)}
 if(counts.level1!==86||counts.level2!==9||!levelMembers.includes(selection.selectedNativeAreaId))fail('selected-membership');
 const scopes=officialPoliceScopes(metricsRaw,'cologne'),scope=scopes.find(s=>s.id===PP);if(scopes.length!==metricsRaw?.areas?.length||!scope||scope.metrics.length!==4)fail('source-scope');
 const rules=rulesRaw?.rules as SourceRule[],descriptors=descriptorsRaw?.descriptors;if(rulesRaw?.schemaVersion!==1||!Array.isArray(rules)||rules.length!==4||descriptorsRaw.scope!==PP||descriptorsRaw.metricDataStoredOnlyInExistingOriginalFile!==true||descriptorsRaw.noValuesCopiedToNativeAreas!==true||!Array.isArray(descriptors)||descriptors.length!==4)fail('source-descriptors');
 const observations:Observation[]=[],concepts=new Set<string>();for(let i=0;i<4;i++){const d=descriptors[i],metric=scope.metrics[i] as typeof scope.metrics[0]&{source_sha256?:string};if(d.city!=='cologne'||d.scope!=='regional'||d.scopeId!==PP||typeof d.conceptId!=='string'||concepts.has(d.conceptId)||!text(d.scopeName)||d.metricReference?.scopeId!==PP||d.metricReference.metricIndex!==i||d.metricReference.fileSHA256!==COLOGNE_BROADER_REFS.metrics.sha256||d.metricReference.path!=='browser-root/crimemaps-Cologne/safety/geography/official-crime-scope-metrics.json'||d.membershipEvidence?.SHA256!==COLOGNE_BROADER_REFS.membership.sha256||!Array.isArray(d.memberAreaIds)||d.memberAreaIds.length!==95||new Set(d.memberAreaIds).size!==95||d.memberAreaIds.some((id:string)=>!all.has(id))||metric.source_sha256!==SOURCE_SHA||metric.source_url!==SOURCE_URL||metric.year!==2025||d.sourceEvidence?.sourceSHA256!==SOURCE_SHA||!same(d.sourceEvidence.fullOriginalDefinition,metric.definition))fail('descriptor-source');
 if(await digest(new TextEncoder().encode(canonical(metric)))!==d.metricReference.recordSHA256)fail('record-sha');const rule=rules.find(r=>r.conceptId===d.conceptId);if(!rule||rule.city!=='cologne'||rule.scope!=='regional'||rule.scopeId!==PP||rule.levels.length!==0||rule.equals.source_sha256!==SOURCE_SHA||rule.equals.source_url!==SOURCE_URL)fail('source-rule');const original=referenceObservation({city:'cologne',scope:'regional',scopeId:PP,scopeName:d.scopeName},metric as unknown as ReferenceMetric,rules);if(!original)fail('source-match');concepts.add(d.conceptId);observations.push({...original,memberAreaIds:levelMembers,membershipEvidence:JSON.stringify(d.membershipEvidence)})}
 return {observations,rules,caption:cologneBroaderReferenceCopy.badge,limitation:cologneBroaderReferenceCopy.note,sourceKind:'police'};
}
export const cologneBroaderReferenceCopy={badge:{zh:'较大警方辖区参考 · 非科隆市或所选分区实测',en:'Broader police-jurisdiction reference · not Cologne city or local measurement',de:'Referenz des größeren Polizeibezugsraums · kein Messwert für Stadt Köln oder Teilgebiet'},note:{zh:'PP Köln统计范围包含科隆和勒沃库森；原始2025年案件数与官方罪案频度保留，不合计PI推算市级值，不分配到分区，也不表示个人受害概率。',en:'PP Köln includes Cologne and Leverkusen. Original 2025 case counts and official crime frequency remain; PI values are not summed to infer a municipal value, allocated to subdivisions or interpreted as individual victimisation probability.',de:'Der Bereich PP Köln umfasst Köln und Leverkusen. Originale Fallzahlen und amtliche KHZ2025 bleiben erhalten; keine PI-Summen als Stadtwert, keine Zuteilung auf Teilgebiete und keine individuelle Opferwahrscheinlichkeit.'}} as const;
/** One typed API; only city-specific reviewed descriptors can add explicit larger-scope observations. */
export async function loadSourceQualifiedBroaderReferences(options:BroaderReferenceOptions):Promise<BroaderReferences>{
 if(options.selection.city==='hannover'){const result=await loadHannoverRegionalReferences(options);return {...result,sourceKind:'regional',caption:{zh:regionalReferenceCopy.zh.badge,en:regionalReferenceCopy.en.badge,de:regionalReferenceCopy.de.badge}}}
 if(options.selection.city==='cologne'){const refs=Object.entries(COLOGNE_BROADER_REFS),raw=[];for(const [name,ref] of refs)raw.push(await readFrozenReferenceAsset(ref,options,name==='metrics'?'no-store':undefined));const result=await parseCologneBroaderReferences(raw[0],raw[1],raw[2],raw[3],options.selection);options.signal.throwIfAborted();return result}
 fail('unreviewed-city');
}
