import {createTransitStopLoader,stopDescriptor,type RouteStopRoster,type StopVariant,type TransitStop} from './transit-route-stops';
import {TRANSIT_STOP_COPY,stopCoverageReasons} from './transit-stop-copy';
import {floatingPosition} from './floating-position';
import type {PublicTransitManifest,TransitMap} from './public-transit-overlay';
import type {PublicTransitMode} from './public-transit-controls';
export type TransitPoint={x:number;y:number};
export type RouteFeature={type:'Feature';properties:Record<string,unknown>;geometry:any};
export interface TransitInteractionMap extends TransitMap {queryRenderedFeatures?(box:any,options:{layers:string[]}):readonly {properties?:Record<string,unknown>}[];getContainer?():HTMLElement;}
export type RouteChoice={key:string;mode:string;routeId:string;features:readonly RouteFeature[];values:Record<string,string>;sourceURL?:string;relationURL?:string;metadataReference:boolean};
const MODES=new Set(['metro','tram','bus','s_bahn','rail','ferry']);
const fields=['ref','name','from','to','operator','source_snapshot'] as const;
const COPY={
 zh:{title:'交通路线信息',close:'关闭',drag:'拖动路线信息框',choose:'此处有多条路线，请选择',route:'路线记录',ref:'线路编号',name:'线路名称',from:'起点',to:'终点',operator:'运营方',date:'数据快照',source:'来源',relation:'OpenStreetMap 路线记录',missing:'当前地图未提供',portion:'高亮显示已加载的路线部分。',noPolice:'交通路线与警方公告分别显示。',metadata:'部分路线资料未在当前地图数据中提供。',previous:'上一页',next:'下一页',page:'页',total:'条路线'},
 en:{title:'Transport route information',close:'Close',drag:'Drag route information',choose:'Multiple routes here; choose one',route:'Route record',ref:'Route number',name:'Route name',from:'From',to:'To',operator:'Operator',date:'Data snapshot',source:'Source',relation:'OpenStreetMap route record',missing:'Not provided in this map data',portion:'The highlight shows the loaded part of the route.',noPolice:'Transport routes are shown separately from police announcements.',metadata:'Some route details are not included in this map data.',previous:'Previous',next:'Next',page:'page',total:'routes'},
 de:{title:'Informationen zur Verkehrslinie',close:'Schließen',drag:'Linieninformationen verschieben',choose:'Mehrere Linien hier; bitte auswählen',route:'Liniendatensatz',ref:'Liniennummer',name:'Linienname',from:'Von',to:'Nach',operator:'Betreiber',date:'Datenstand',source:'Quelle',relation:'OpenStreetMap-Liniendatensatz',missing:'In diesen Kartendaten nicht angegeben',portion:'Hervorgehoben wird der geladene Teil der Linie.',noPolice:'Verkehrslinien werden getrennt von Polizeimeldungen angezeigt.',metadata:'Einige Linienangaben sind in diesen Kartendaten nicht enthalten.',previous:'Zurück',next:'Weiter',page:'Seite',total:'Linien'}
};
function value(v:unknown):string|undefined{return typeof v==='string'&&v.trim()?v.trim().slice(0,400):typeof v==='number'&&Number.isFinite(v)?String(v):undefined;}
export function safeTransitURL(v:unknown):string|undefined{if(typeof v!=='string')return;try{const u=new URL(v);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href;}catch{}return;}
const key=(p:Record<string,unknown>)=>MODES.has(String(p.mode))&&typeof p.route_id==='string'&&p.route_id.trim()?String(p.mode)+'\0'+p.route_id:undefined;
/** Hits identify loaded source records only; tiled segments sharing route_id become one choice. */
export function transitChoices(loaded:readonly RouteFeature[],hits:readonly {properties?:Record<string,unknown>}[],manifest?:PublicTransitManifest):RouteChoice[]{
 const wanted=new Set(hits.map(h=>h.properties&&key(h.properties)).filter(Boolean));const groups=new Map<string,RouteFeature[]>();
 for(const f of loaded){const k=key(f.properties);if(!k||!wanted.has(k))continue;const g=groups.get(k)??[];g.push(f);groups.set(k,g);}
 return [...groups].map(([k,features])=>{const p=features[0].properties,mode=String(p.mode),meta=manifest?.modes[mode as PublicTransitMode],values:Record<string,string>={};
  for(const field of fields){const valuesFound=[...new Set(features.map(f=>value(f.properties[field])).filter((v):v is string=>!!v))];if(valuesFound.length)values[field]=valuesFound.slice(0,4).join(' / ');}
  // GTFS short/long names are real fields, not names manufactured from the route number.
  if(!values.ref){const v=value(p.route_short_name);if(v)values.ref=v;}if(!values.name){const v=value(p.route_long_name);if(v)values.name=v;}
  if(!values.source_snapshot&&meta?.reference_date)values.source_snapshot=meta.reference_date;
  const sourceURL=features.map(f=>safeTransitURL(f.properties.source_url)).find(Boolean)??safeTransitURL(meta?.source?.url);if(meta?.source?.name)values.source=meta.source.name;
  const relation=value(p.relation_id),relationURL=relation&&/^\d+$/.test(relation)?'https://www.openstreetmap.org/relation/'+relation:undefined;
  return {key:k,mode,routeId:String(p.route_id),features,values,sourceURL,relationURL,metadataReference:features.some(f=>typeof f.properties.provenance_sidecar==='string')};
 }).sort((a,b)=>(a.values.ref??a.routeId).localeCompare(b.values.ref??b.routeId)||a.key.localeCompare(b.key));
}
export function publicTransitRecordId(id:string):string|undefined{return id.length<=100&&!/[a-f0-9]{32,}/i.test(id)?id:undefined;}
export function transitPanelViewport(map:{left:number;top:number;right:number;bottom:number},v:{left:number;top:number;width:number;height:number}){const left=Math.max(map.left,v.left),top=Math.max(map.top,v.top),right=Math.min(map.right,v.left+v.width),bottom=Math.min(map.bottom,v.top+v.height);return right-left>=48&&bottom-top>=48?{left,top,width:right-left,height:bottom-top}:v;}
const SOURCE='public-transit-selected-route',HALO='public-transit-selected-halo',LINE='public-transit-selected-line';
export function installTransitInteraction(options:{map:TransitInteractionMap;host:HTMLElement;locale:'zh'|'en'|'de';city?:string;isRefreshing?:(mode:PublicTransitMode)=>boolean;isRouteVisible?:(route:RouteChoice)=>boolean;fetchBytes?:(path:string,signal:AbortSignal,maxBytes:number)=>Promise<Uint8Array>;loaded:()=>readonly RouteFeature[];manifest:()=>PublicTransitManifest|undefined}){
 const {map,host,locale}=options,c=COPY[locale],sc=TRANSIT_STOP_COPY[locale];
 const stopLoader=options.fetchBytes?createTransitStopLoader(options.fetchBytes):undefined;let stopAbort=new AbortController(),stopRevision=0,stopData:RouteStopRoster|undefined,variantIndex=0,stopPage=0,stopListOpen=false,sourceDetailsOpen=false,selectedStop:number|undefined,stopContext='',stopState:'missing'|'loading'|'ready'|'error'='missing';
 const STOP_SOURCE='public-transit-selected-stops',STOP_POINT='public-transit-selected-stop-points',STOP_LABEL='public-transit-selected-stop-labels',STOP_ACTIVE='public-transit-selected-stop-active';let selected:RouteChoice|undefined,choices:RouteChoice[]=[],page=0,destroyed=false,positioned=false;
 const panel=document.createElement('section');panel.hidden=true;panel.className='geography-panel transit-route-inspector';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',c.title);
 const handle=document.createElement('header');handle.className='geography-drag transit-route-drag';handle.tabIndex=0;handle.setAttribute('aria-label',c.drag);const heading=document.createElement('strong');heading.textContent=c.title;
 const close=document.createElement('button');close.type='button';close.className='transit-route-close';close.textContent='×';close.setAttribute('aria-label',c.close);close.onclick=()=>clear();handle.append(heading,close);
 const body=document.createElement('div');body.className='geography-panel-body transit-route-body';panel.append(handle,body);document.body.append(panel);panel.addEventListener('click',e=>e.stopPropagation());panel.addEventListener('pointerdown',e=>e.stopPropagation());
 let drag:{x:number;y:number;left:number;top:number}|undefined;
 const viewport=()=>{const v=window.visualViewport;return {left:v?.offsetLeft??0,top:v?.offsetTop??0,width:v?.width??innerWidth,height:v?.height??innerHeight};};
 const bounds=()=>transitPanelViewport(host.getBoundingClientRect(),viewport());
 function move(left:number,top:number){const b=bounds();panel.style.width=Math.max(0,Math.min(280,b.width-24))+'px';panel.style.maxWidth=Math.max(0,b.width-24)+'px';panel.style.maxHeight=Math.max(0,Math.min(320,b.height-24,b.width<=760?b.height*.6:Infinity))+'px';const at=floatingPosition(left,top,panel.offsetWidth,panel.offsetHeight,b);panel.style.left=at.left+'px';panel.style.top=at.top+'px';panel.style.right='auto';panel.style.bottom='auto';}
 function clamp(){if(panel.hidden)return;const b=bounds(),r=panel.getBoundingClientRect();move(positioned?r.left:b.left+b.width-292,positioned?r.top:b.top+24);positioned=true;}
 handle.onpointerdown=e=>{if((e.target as HTMLElement).closest('button'))return;const r=panel.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};handle.setPointerCapture(e.pointerId);};
 handle.onpointermove=e=>{if(drag)move(drag.left+e.clientX-drag.x,drag.top+e.clientY-drag.y);};handle.onpointerup=handle.onpointercancel=()=>{drag=undefined;};
 handle.onkeydown=e=>{const delta:Record<string,number[]>={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(delta[e.key]){e.preventDefault();const r=panel.getBoundingClientRect();move(r.left+delta[e.key][0],r.top+delta[e.key][1]);}};
 panel.onkeydown=e=>{if(e.key==='Escape')clear();};window.addEventListener('resize',clamp);window.addEventListener('scroll',clamp,{passive:true});window.visualViewport?.addEventListener('resize',clamp);window.visualViewport?.addEventListener('scroll',clamp);map.on('resize',clamp);
 const empty=()=>({type:'FeatureCollection',features:[]});
 function setup(){if(!map.getSource(SOURCE))map.addSource(SOURCE,{type:'geojson',data:empty()});if(!map.getLayer(HALO))map.addLayer({id:HALO,type:'line',source:SOURCE,paint:{'line-color':'#172c3f','line-width':7,'line-opacity':.7}});if(!map.getLayer(LINE))map.addLayer({id:LINE,type:'line',source:SOURCE,paint:{'line-color':'#f2c779','line-width':4,'line-opacity':1}});}
 function clear(){stopAbort.abort();stopRevision++;stopData=undefined;selectedStop=undefined;stopState='missing';map.getSource(STOP_SOURCE)?.setData(empty());selected=undefined;choices=[];page=0;drag=undefined;panel.hidden=true;body.replaceChildren();map.getSource(SOURCE)?.setData(empty());}
 function draw(){body.replaceChildren();panel.hidden=false;
  if(choices.length>1){const label=document.createElement('p');label.textContent=c.choose;body.append(label);const pages=Math.ceil(choices.length/20);page=Math.min(page,pages-1);const pager=document.createElement('div');pager.className='transit-route-pager';const counter=document.createElement('span');counter.textContent=choices.length+' '+c.total+' · '+c.page+' '+(page+1)+'/'+pages;pager.append(counter);if(pages>1){for(const [label,offset]of [[c.previous,-1],[c.next,1]] as const){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=page+offset<0||page+offset>=pages;b.className='transit-route-page-button';b.onclick=()=>{page+=offset;draw();};pager.append(b);}}body.append(pager);for(const r of choices.slice(page*20,page*20+20)){const b=document.createElement('button');b.type='button';b.textContent=[r.values.ref,r.values.name].filter(Boolean).join(' · ')||publicTransitRecordId(r.routeId)||c.missing;b.setAttribute('aria-pressed',String(r.key===selected?.key));b.className='transit-route-choice';b.onclick=()=>select(r);body.append(b);}}
  if(selected){const identity=document.createElement('dl');identity.className='transit-route-fields transit-route-identity';for(const [label,val]of [[c.ref,selected.values.ref],[c.name,selected.values.name]]as const){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=val??c.missing;identity.append(dt,dd);}body.append(identity);drawStops();drawSourceDetails();}
  for(const text of [c.portion,c.noPolice]){const p=document.createElement('p');p.textContent=text;body.append(p);}
  clamp();
 }


 function drawSourceDetails(){if(!selected)return;const v=variant(),details=document.createElement('details');details.className='transit-route-source-details';details.open=sourceDetailsOpen;details.ontoggle=()=>{sourceDetailsOpen=details.open;};const summary=document.createElement('summary'),date=v?.reference_date??selected.values.source_snapshot;summary.textContent=sc.sourceDetails+(date?' · '+(/^\d{4}-\d{2}-\d{2}/.test(date)?date.slice(0,10):date):'');details.append(summary);const dl=document.createElement('dl');dl.className='transit-route-fields';
  const fields:[string,string|undefined][]=[[c.operator,selected.values.operator],[c.source,v?.source.name??selected.values.source],[v?sc.date:c.date,date]];
  const id=publicTransitRecordId(selected.routeId);if(id)fields.push([c.route,id]);
  if(v&&selected.values.source_snapshot&&selected.values.source_snapshot!==v.reference_date)fields.push([c.date,selected.values.source_snapshot]);
  if(!v?.start_stop_id&&selected.values.from)fields.push([sc.sourceFrom,selected.values.from]);if(!v?.end_stop_id&&selected.values.to)fields.push([sc.sourceTo,selected.values.to]);
  for(const [label,value]of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value??c.missing;dl.append(dt,dd);}details.append(dl);if(v?.coverage_note?.[locale]){const note=document.createElement('p');note.className='transit-route-specific-coverage';note.textContent=v.coverage_note[locale];details.append(note);}
  const links=new Set<string>();for(const [url,label]of [[v?.source.url,sc.source],[selected.sourceURL,c.source],[selected.relationURL,c.relation]]as const){if(url&&!links.has(url)){links.add(url);const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.className='transit-route-source';details.append(a);}}
  if(selected.metadataReference){const p=document.createElement('p');p.textContent=c.metadata;details.append(p);}body.append(details);
 }

 function variant():StopVariant|undefined{return stopData?.variants[variantIndex];}
 function routeFeatures(){const v=variant();if(!selected)return[];if(!v)return selected.features;if(v.shape_ids)return selected.features.filter(f=>v.shape_ids!.includes(String(f.properties.shape_id)));return stopData!.variants.length===1?selected.features:[];}
 function drawStopMap(){const v=variant();if(!selected||!v){map.getSource(STOP_SOURCE)?.setData(empty());return;}if(!map.getSource(STOP_SOURCE))map.addSource(STOP_SOURCE,{type:'geojson',data:empty()});
  if(!map.getLayer(STOP_POINT))map.addLayer({id:STOP_POINT,type:'circle',source:STOP_SOURCE,paint:{'circle-radius':4,'circle-color':'#f2c779','circle-stroke-color':'#172c3f','circle-stroke-width':.8}});
  if(!map.getLayer(STOP_LABEL))map.addLayer({id:STOP_LABEL,type:'symbol',source:STOP_SOURCE,layout:{'text-field':['get','display_name'],'text-size':10,'text-font':['Open Sans Regular','Arial Unicode MS Regular'],'text-offset':[0,1.1],'text-anchor':'top'},paint:{'text-color':'#172c3f','text-halo-color':'#fff','text-halo-width':1}});
  if(!map.getLayer(STOP_ACTIVE))map.addLayer({id:STOP_ACTIVE,type:'circle',source:STOP_SOURCE,paint:{'circle-radius':6,'circle-color':'#f2c779','circle-stroke-color':'#172c3f','circle-stroke-width':2}});
  map.setFilter(STOP_ACTIVE,['==',['get','sequence'],selectedStop??-1]);
  map.getSource(STOP_SOURCE).setData({type:'FeatureCollection',features:v.stops.filter(s=>s.coordinates!==null).map(s=>({type:'Feature',geometry:{type:'Point',coordinates:s.coordinates},properties:{route_id:selected!.routeId,variant_id:v.variant_id,stop_id:s.stop_id,sequence:s.sequence,display_name:(selected!.values.ref?selected!.values.ref+' · ':'')+s.sequence+'. '+(s.name??sc.nameMissing)+(s.city_scope==='out_of_city'?' · '+sc.outside:s.city_scope==='uncertain'?' · '+sc.scopeUnknown:'')}}))});
  map.getSource(SOURCE)?.setData({type:'FeatureCollection',features:routeFeatures()});
 }
 function context(r:RouteChoice){const m=options.manifest(),e=m?.modes[r.mode as PublicTransitMode];return JSON.stringify([m?.city,e?.status,e?.source?.sha256,e?.source?.url,e?.reference_date,e?.stop_lists_index]);}
 function beginStops(r:RouteChoice){stopAbort.abort();stopAbort=new AbortController();const revision=++stopRevision,signal=stopAbort.signal;stopData=undefined;stopContext=context(r);variantIndex=0;stopPage=0;stopListOpen=false;sourceDetailsOpen=false;selectedStop=undefined;map.getSource(STOP_SOURCE)?.setData(empty());
  const manifest=options.manifest(),mode=r.mode as PublicTransitMode,entry=manifest?.modes[mode],descriptor=entry?.stop_lists_index;stopState='missing';if(!stopLoader||!manifest||entry?.status!=='available'||!stopDescriptor(descriptor))return;
  stopState='loading';void stopLoader.load(options.city??manifest.city,mode,r.routeId,descriptor,signal).then(data=>{if(destroyed||signal.aborted||revision!==stopRevision||selected?.key!==r.key)return;const now=options.manifest()?.modes[mode];if(now?.status!=='available'||now.stop_lists_index?.sha256!==descriptor.sha256||now.stop_lists_index?.path!==descriptor.path||now.stop_lists_index?.bytes!==descriptor.bytes){stopState='missing';draw();return;}if(!transitChoices(options.loaded(),[{properties:{mode:r.mode,route_id:r.routeId}}],options.manifest()).length){clear();return;}if(data&&data.variants.some(v=>v.source.sha256!==entry.source?.sha256))throw Error('Stop source does not match selected route source');stopData=data;stopState=data?'ready':'missing';drawStopMap();draw();}).catch(()=>{if(destroyed||signal.aborted||revision!==stopRevision)return;stopState='error';draw();});
 }
 function chooseStop(stop:TransitStop){selectedStop=stop.sequence;drawStopMap();draw();}
 function inspectStop(point:TransitPoint){const v=variant();if(destroyed||!Number.isFinite(point.x)||!Number.isFinite(point.y)||!v||!selected||!map.queryRenderedFeatures||!map.getLayer(STOP_POINT))return false;
  const box:[[number,number],[number,number]]=[[point.x-6,point.y-6],[point.x+6,point.y+6]];
  // Marker hits take priority over neighbouring text labels; both retain exact source identity.
  for(const group of [[STOP_ACTIVE,STOP_POINT],[STOP_LABEL]]){const layers=group.filter(id=>map.getLayer(id));if(!layers.length)continue;let hits;try{hits=map.queryRenderedFeatures(box,{layers});}catch{return false;}
   for(const hit of hits){const p=hit.properties;if(p?.route_id!==selected.routeId||p.variant_id!==v.variant_id)continue;const stop=v.stops.find(s=>s.stop_id===p.stop_id&&s.sequence===p.sequence&&s.coordinates!==null);if(stop){chooseStop(stop);return true;}}
  }return false;
 }
 function drawStops(){const section=document.createElement('section');section.className='transit-route-stops';const title=document.createElement('strong');title.textContent=sc.heading;section.append(title);body.append(section);
  if(stopState!=='ready'||!stopData){const endpoints=document.createElement('dl');endpoints.className='transit-route-fields transit-route-endpoints';for(const [label,gap]of [[sc.start,sc.startMissing],[sc.end,sc.endMissing]]as const){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=stopState==='loading'?sc.pendingEndpoint:gap;endpoints.append(dt,dd);}section.append(endpoints);const p=document.createElement('p');p.textContent=stopState==='loading'?sc.loading:stopState==='error'?sc.error:sc.missing;section.append(p);if(stopState==='error'){const retry=document.createElement('button');retry.type='button';retry.className='transit-route-choice';retry.textContent=sc.retry;retry.onclick=()=>{if(selected){beginStops(selected);draw();}};section.append(retry);}return;}
  const v=variant()!;const direction=document.createElement('p');direction.textContent=sc.direction+': '+(v.direction??sc.directionMissing);section.append(direction);
  if(stopData.variants.length>1)for(const [i,entry]of stopData.variants.entries()){const b=document.createElement('button');b.type='button';b.className='transit-route-choice';b.textContent=entry.direction??sc.variant+' '+(i+1);b.setAttribute('aria-pressed',String(i===variantIndex));b.onclick=()=>{variantIndex=i;stopPage=0;selectedStop=undefined;drawStopMap();draw();};section.append(b);}
  const endpoints=document.createElement('dl');endpoints.className='transit-route-fields transit-route-endpoints';for(const [label,id,missing]of [[sc.start,v.start_stop_id,sc.startMissing],[sc.end,v.end_stop_id,sc.endMissing]]as const){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;const stop=id?v.stops.find(s=>s.stop_id===id):undefined;dd.textContent=stop?(stop.name??sc.nameMissing)+(stop.city_scope==='out_of_city'?' · '+sc.outside:stop.city_scope==='uncertain'?' · '+sc.scopeUnknown:''):missing;endpoints.append(dt,dd);}section.append(endpoints);
  const chosen=v.stops.find(s=>s.sequence===selectedStop);if(chosen){const detail=document.createElement('div');detail.className='transit-route-stop-detail';const label=document.createElement('strong');label.textContent=sc.selected+': '+(chosen.name??sc.nameMissing);const p=document.createElement('p');p.textContent=sc.order+': '+chosen.sequence+(chosen.city_scope==='out_of_city'?' · '+sc.outside:chosen.city_scope==='uncertain'?' · '+sc.scopeUnknown:'');detail.append(label,p);if(chosen.coordinates===null){const p=document.createElement('p');p.textContent=sc.coordinateMissing;detail.append(p);}const link=document.createElement('a');link.textContent=sc.source;link.href=chosen.source_url??v.source.url;link.target='_blank';link.rel='noopener noreferrer';detail.append(link);section.append(detail);}
  const details=document.createElement('details');details.className='transit-route-stop-list';details.open=stopListOpen;details.ontoggle=()=>{stopListOpen=details.open;};const summary=document.createElement('summary');summary.textContent=sc.ordered+' · '+v.stops.length+' '+sc.station+(v.stops.length?' · '+sc.preview+': '+v.stops.slice(0,2).map(s=>s.name??sc.nameMissing).join(' / '):'');details.append(summary);const pages=Math.max(1,Math.ceil(v.stops.length/20));stopPage=Math.min(stopPage,pages-1);if(pages>1){const pager=document.createElement('div');pager.className='transit-route-pager';const count=document.createElement('span');count.textContent=sc.page+' '+(stopPage+1)+'/'+pages;pager.append(count);for(const [label,offset]of [[sc.previous,-1],[sc.next,1]]as const){const b=document.createElement('button');b.type='button';b.className='transit-route-page-button';b.textContent=label;b.disabled=stopPage+offset<0||stopPage+offset>=pages;b.onclick=()=>{stopPage+=offset;stopListOpen=true;draw();};pager.append(b);}details.append(pager);}
  for(const stop of v.stops.slice(stopPage*20,stopPage*20+20)){const b=document.createElement('button');b.type='button';b.className='transit-route-choice transit-route-stop-choice';b.textContent=stop.sequence+'. '+(stop.name??sc.nameMissing)+(stop.city_scope==='out_of_city'?' · '+sc.outside:stop.city_scope==='uncertain'?' · '+sc.scopeUnknown:'');b.setAttribute('aria-pressed',String(stop.sequence===selectedStop));b.onclick=()=>chooseStop(stop);details.append(b);}section.append(details);const coverage=document.createElement('p');coverage.className='transit-route-coverage';coverage.textContent=(v.complete?sc.complete:sc.partial)+' '+stopCoverageReasons(v,locale).join(' ');section.append(coverage);if(stopData.variants.length>1&&!v.shape_ids){const p=document.createElement('p');p.textContent=sc.geometryMissing;section.append(p);}
 }

 function select(r:RouteChoice){const fresh=transitChoices(options.loaded(),[{properties:{mode:r.mode,route_id:r.routeId}}],options.manifest())[0];if(!fresh){clear();return;}selected=fresh;setup();map.getSource(SOURCE).setData({type:'FeatureCollection',features:fresh.features});beginStops(fresh);draw();}
 return {inspect(point:TransitPoint):boolean{if(destroyed||!map.queryRenderedFeatures||!Number.isFinite(point.x)||!Number.isFinite(point.y))return false;if(inspectStop(point))return true;const layers=['metro','tram','bus','extra'].map(g=>'public-transit-'+g+'-lines').filter(id=>map.getLayer(id));if(!layers.length){clear();return false;}let hits;try{hits=map.queryRenderedFeatures([[point.x-6,point.y-6],[point.x+6,point.y+6]],{layers});}catch{clear();return false;}choices=transitChoices(options.loaded(),hits,options.manifest());page=0;if(!choices.length){clear();return false;}select(choices[0]);return true;},inspectStop,clear,update(){if(!selected)return;if(options.isRefreshing?.(selected.mode as PublicTransitMode)&&stopContext===context(selected))return;const hit=[{properties:{mode:selected.mode,route_id:selected.routeId}}],fresh=transitChoices(options.loaded(),hit,options.manifest())[0];if(!fresh||(options.isRouteVisible&&!options.isRouteVisible(fresh))){clear();return;}if(stopContext===context(fresh)&&selected.features.length===fresh.features.length&&selected.features.every((f,i)=>f===fresh.features[i]))return;selected=fresh;if(stopContext!==context(fresh))beginStops(fresh);choices=transitChoices(options.loaded(),choices.map(r=>({properties:{mode:r.mode,route_id:r.routeId}})),options.manifest());setup();map.getSource(SOURCE).setData({type:'FeatureCollection',features:routeFeatures()});draw();},destroy(){if(destroyed)return;clear();destroyed=true;window.removeEventListener('resize',clamp);window.removeEventListener('scroll',clamp);window.visualViewport?.removeEventListener('resize',clamp);window.visualViewport?.removeEventListener('scroll',clamp);map.off('resize',clamp);stopLoader?.clear();panel.remove();for(const id of [STOP_ACTIVE,STOP_LABEL,STOP_POINT,LINE,HALO])if(map.getLayer(id))map.removeLayer(id);if(map.getSource(STOP_SOURCE))map.removeSource(STOP_SOURCE);if(map.getSource(SOURCE))map.removeSource(SOURCE);},get selection(){return selected;},get choiceCount(){return choices.length;}};
}
