export const TRANSIT_STOP_COPY={
 zh:{sourceDetails:'来源与路线资料',sourceFrom:'来源中的起点描述',sourceTo:'来源中的终点描述',pendingEndpoint:'正在读取来源',missingMembers:'部分来源站点资料缺失。',unpairedPlatforms:'有些站台与所列停靠站点的对应关系尚未确认。',orderUnverified:'来源提供的停靠顺序尚未完整核验。',heading:'线路站点',preview:'预览',loading:'正在读取这条路线的站序…',missing:'这条路线的站序未提供。',error:'站点信息未能读取。',retry:'重试',direction:'方向／路线变体',directionMissing:'来源未注明方向',variant:'路线变体',start:'起点站',end:'终点站',startMissing:'来源未确认起点站',endMissing:'来源未确认终点站',ordered:'中途及沿线站点',complete:'来源中的已核验完整站序；不代表实时运营信息。',partial:'仅显示已核验的部分站序，不能当作全线站单。',selected:'所选站点',order:'来源站序',outside:'市外',scopeUnknown:'所属城市未确认',nameMissing:'来源未提供站名',coordinateMissing:'来源坐标未提供，地图不补画站点。',source:'站序来源',date:'站序快照',geometryMissing:'来源未绑定这个方向的线路几何，地图不混画其他方向。',previous:'上一页',next:'下一页',page:'页',station:'站'},
 en:{sourceDetails:'Sources and route details',sourceFrom:'Start description in the source',sourceTo:'End description in the source',pendingEndpoint:'Reading the source',missingMembers:'Some source stop details are missing.',unpairedPlatforms:'Some platforms could not be matched confidently to the listed stops.',orderUnverified:'The stop order provided by the source has not been fully verified.',heading:'Route stops',preview:'preview',loading:'Loading the stop order for this route…',missing:'The stop order for this route is not provided.',error:'Stop information could not be loaded.',retry:'Retry',direction:'Direction / route variant',directionMissing:'Direction not stated by the source',variant:'Route variant',start:'Start stop',end:'End stop',startMissing:'Start stop not confirmed by the source',endMissing:'End stop not confirmed by the source',ordered:'Intermediate and route stops',complete:'The complete verified order in the source; not live service information.',partial:'Only part of the stop order is verified; this is not a full route stop list.',selected:'Selected stop',order:'Source stop order',outside:'Outside the city',scopeUnknown:'City scope unconfirmed',nameMissing:'Stop name not provided by the source',coordinateMissing:'Source coordinates are missing; no stop point is added to the map.',source:'Stop-order source',date:'Stop-order snapshot',geometryMissing:'The source does not bind line geometry to this direction; other directions are not drawn together.',previous:'Previous',next:'Next',page:'page',station:'stops'},
 de:{sourceDetails:'Quellen und Linienangaben',sourceFrom:'Anfangsbeschreibung der Quelle',sourceTo:'Endbeschreibung der Quelle',pendingEndpoint:'Quelle wird gelesen',missingMembers:'Einige Haltestellenangaben der Quelle fehlen.',unpairedPlatforms:'Einige Bahnsteige konnten den aufgeführten Halten nicht eindeutig zugeordnet werden.',orderUnverified:'Die Haltestellenfolge der Quelle ist noch nicht vollständig geprüft.',heading:'Haltestellen der Linie',preview:'Vorschau',loading:'Die Haltestellenfolge dieser Linie wird geladen…',missing:'Die Haltestellenfolge dieser Linie ist nicht angegeben.',error:'Haltestelleninformationen konnten nicht geladen werden.',retry:'Erneut versuchen',direction:'Richtung / Linienvariante',directionMissing:'Richtung in der Quelle nicht angegeben',variant:'Linienvariante',start:'Anfangshaltestelle',end:'Endhaltestelle',startMissing:'Anfangshaltestelle durch Quelle nicht bestätigt',endMissing:'Endhaltestelle durch Quelle nicht bestätigt',ordered:'Zwischenhalte und Haltestellenfolge',complete:'Vollständig geprüfte Haltestellenfolge der Quelle; keine aktuellen Betriebsinformationen.',partial:'Nur ein Teil der Haltestellenfolge ist geprüft; dies ist keine vollständige Haltestellenliste.',selected:'Ausgewählte Haltestelle',order:'Reihenfolge laut Quelle',outside:'Außerhalb der Stadt',scopeUnknown:'Stadtzuordnung ungeklärt',nameMissing:'Haltestellenname in der Quelle nicht angegeben',coordinateMissing:'Quellkoordinaten fehlen; kein Haltepunkt wird auf der Karte ergänzt.',source:'Quelle der Haltestellenfolge',date:'Datenstand der Haltestellenfolge',geometryMissing:'Die Quelle ordnet dieser Richtung keine Liniengeometrie zu; andere Richtungen werden nicht vermischt dargestellt.',previous:'Zurück',next:'Weiter',page:'Seite',station:'Haltestellen'}
};

/** Public wording from explicit source limitation fields; methods remain in rules/evidence. */
export function stopCoverageReasons(variant:{complete:boolean},locale:'zh'|'en'|'de'):string[]{
 if(variant.complete)return[];const copy=TRANSIT_STOP_COPY[locale],source=variant as {missing_members?:unknown;unmatched_platform_members?:unknown;order_basis?:unknown;source_relation_tags?:Record<string,unknown>};const reasons:string[]=[];
 if(Array.isArray(source.missing_members)&&source.missing_members.length)reasons.push(copy.missingMembers);
 if(Array.isArray(source.unmatched_platform_members)&&source.unmatched_platform_members.length)reasons.push(copy.unpairedPlatforms);
 if((typeof source.order_basis==='string'&&/PTv1|legacy/i.test(source.order_basis))||source.source_relation_tags?.['public_transport:version']==='1')reasons.push(copy.orderUnverified);
 if(!reasons.length)reasons.push(copy.orderUnverified);return reasons;
}
