import {floatingPosition} from './floating-position';
import type {PublicTransitManifest,TransitMap} from './public-transit-overlay';
import type {PublicTransitMode} from './public-transit-controls';
export type TransitPoint={x:number;y:number};
export type RouteFeature={type:'Feature';properties:Record<string,unknown>;geometry:any};
export interface TransitInteractionMap extends TransitMap {queryRenderedFeatures?(box:any,options:{layers:string[]}):readonly {properties?:Record<string,unknown>}[];getContainer?():HTMLElement;}
export type RouteChoice={key:string;mode:string;routeId:string;features:readonly RouteFeature[];values:Record<string,string>;sourceURL?:string;relationURL?:string;metadataReference:boolean};
const MODES=new Set(['metro','tram','bus','s_bahn','rail','ferry']);
const fields=['ref','name','from','to','operator','source_snapshot'] as const;
const COPY={
 zh:{title:'交通路线信息',close:'关闭',drag:'拖动路线信息框',choose:'此处有多条路线，请选择',route:'路线记录',ref:'线路编号',name:'线路名称',from:'起点',to:'终点',operator:'运营方',date:'数据快照',source:'来源',relation:'OpenStreetMap 路线记录',missing:'当前地图未提供',portion:'高亮显示已加载的路线部分。',noPolice:'交通路线与警方公告分别显示。',metadata:'部分路线资料未在当前地图数据中提供。',previous:'上一页',next:'下一页',page:'页',total:'条路线'},
 en:{title:'Transport route information',close:'Close',drag:'Drag route information',choose:'Multiple routes here; choose one',route:'Route record',ref:'Route number',name:'Route name',from:'From',to:'To',operator:'Operator',date:'Data snapshot',source:'Source',relation:'OpenStreetMap route record',missing:'Not provided in this map data',portion:'The highlight shows the loaded part of the route.',noPolice:'Transport routes are shown separately from police announcements.',metadata:'Some route details are not included in this map data.',previous:'Previous',next:'Next',page:'page',total:'routes'},
 de:{title:'Informationen zur Verkehrslinie',close:'Schließen',drag:'Linieninformationen verschieben',choose:'Mehrere Linien hier; bitte auswählen',route:'Liniendatensatz',ref:'Liniennummer',name:'Linienname',from:'Von',to:'Nach',operator:'Betreiber',date:'Datenstand',source:'Quelle',relation:'OpenStreetMap-Liniendatensatz',missing:'In diesen Kartendaten nicht angegeben',portion:'Hervorgehoben wird der geladene Teil der Linie.',noPolice:'Verkehrslinien werden getrennt von Polizeimeldungen angezeigt.',metadata:'Einige Linienangaben sind in diesen Kartendaten nicht enthalten.',previous:'Zurück',next:'Weiter',page:'Seite',total:'Linien'}
};
function value(v:unknown):string|undefined{return typeof v==='string'&&v.trim()?v.trim().slice(0,400):typeof v==='number'&&Number.isFinite(v)?String(v):undefined;}
export function safeTransitURL(v:unknown):string|undefined{if(typeof v!=='string')return;try{const u=new URL(v);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href;}catch{}return;}
const key=(p:Record<string,unknown>)=>MODES.has(String(p.mode))&&typeof p.route_id==='string'&&p.route_id.trim()?String(p.mode)+'\0'+p.route_id:undefined;
/** Hits identify loaded source records only; tiled segments sharing route_id become one choice. */
export function transitChoices(loaded:readonly RouteFeature[],hits:readonly {properties?:Record<string,unknown>}[],manifest?:PublicTransitManifest):RouteChoice[]{
 const wanted=new Set(hits.map(h=>h.properties&&key(h.properties)).filter(Boolean));const groups=new Map<string,RouteFeature[]>();
 for(const f of loaded){const k=key(f.properties);if(!k||!wanted.has(k))continue;const g=groups.get(k)??[];g.push(f);groups.set(k,g);}
 return [...groups].map(([k,features])=>{const p=features[0].properties,mode=String(p.mode),meta=manifest?.modes[mode as PublicTransitMode],values:Record<string,string>={};
  for(const field of fields){const valuesFound=[...new Set(features.map(f=>value(f.properties[field])).filter((v):v is string=>!!v))];if(valuesFound.length)values[field]=valuesFound.slice(0,4).join(' / ');}
  // GTFS short/long names are real fields, not names manufactured from the route number.
  if(!values.ref){const v=value(p.route_short_name);if(v)values.ref=v;}if(!values.name){const v=value(p.route_long_name);if(v)values.name=v;}
  if(!values.source_snapshot&&meta?.reference_date)values.source_snapshot=meta.reference_date;
  const sourceURL=features.map(f=>safeTransitURL(f.properties.source_url)).find(Boolean)??safeTransitURL(meta?.source?.url);if(meta?.source?.name)values.source=meta.source.name;
  const relation=value(p.relation_id),relationURL=relation&&/^\d+$/.test(relation)?'https://www.openstreetmap.org/relation/'+relation:undefined;
  return {key:k,mode,routeId:String(p.route_id),features,values,sourceURL,relationURL,metadataReference:features.some(f=>typeof f.properties.provenance_sidecar==='string')};
 }).sort((a,b)=>(a.values.ref??a.routeId).localeCompare(b.values.ref??b.routeId)||a.key.localeCompare(b.key));
}
export function publicTransitRecordId(id:string):string|undefined{return id.length<=100&&!/[a-f0-9]{32,}/i.test(id)?id:undefined;}
export function transitPanelViewport(map:{left:number;top:number;right:number;bottom:number},v:{left:number;top:number;width:number;height:number}){const left=Math.max(map.left,v.left),top=Math.max(map.top,v.top),right=Math.min(map.right,v.left+v.width),bottom=Math.min(map.bottom,v.top+v.height);return right-left>=48&&bottom-top>=48?{left,top,width:right-left,height:bottom-top}:v;}
const SOURCE='public-transit-selected-route',HALO='public-transit-selected-halo',LINE='public-transit-selected-line';
export function installTransitInteraction(options:{map:TransitInteractionMap;host:HTMLElement;locale:'zh'|'en'|'de';loaded:()=>readonly RouteFeature[];manifest:()=>PublicTransitManifest|undefined}){
 const {map,host,locale}=options,c=COPY[locale];let selected:RouteChoice|undefined,choices:RouteChoice[]=[],page=0,destroyed=false,positioned=false;
 const panel=document.createElement('section');panel.hidden=true;panel.className='geography-panel transit-route-inspector';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',c.title);
 const handle=document.createElement('header');handle.className='geography-drag transit-route-drag';handle.tabIndex=0;handle.setAttribute('aria-label',c.drag);const heading=document.createElement('strong');heading.textContent=c.title;
 const close=document.createElement('button');close.type='button';close.className='transit-route-close';close.textContent='×';close.setAttribute('aria-label',c.close);close.onclick=()=>clear();handle.append(heading,close);
 const body=document.createElement('div');body.className='geography-panel-body transit-route-body';panel.append(handle,body);document.body.append(panel);panel.addEventListener('click',e=>e.stopPropagation());panel.addEventListener('pointerdown',e=>e.stopPropagation());
 let drag:{x:number;y:number;left:number;top:number}|undefined;
 const viewport=()=>{const v=window.visualViewport;return {left:v?.offsetLeft??0,top:v?.offsetTop??0,width:v?.width??innerWidth,height:v?.height??innerHeight};};
 const bounds=()=>transitPanelViewport(host.getBoundingClientRect(),viewport());
 function move(left:number,top:number){const b=bounds();panel.style.width=Math.max(0,Math.min(280,b.width-24))+'px';panel.style.maxWidth=Math.max(0,b.width-24)+'px';panel.style.maxHeight=Math.max(0,Math.min(320,b.height-24,b.width<=760?b.height*.6:Infinity))+'px';const at=floatingPosition(left,top,panel.offsetWidth,panel.offsetHeight,b);panel.style.left=at.left+'px';panel.style.top=at.top+'px';panel.style.right='auto';panel.style.bottom='auto';}
 function clamp(){if(panel.hidden)return;const b=bounds(),r=panel.getBoundingClientRect();move(positioned?r.left:b.left+b.width-292,positioned?r.top:b.top+24);positioned=true;}
 handle.onpointerdown=e=>{if((e.target as HTMLElement).closest('button'))return;const r=panel.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};handle.setPointerCapture(e.pointerId);};
 handle.onpointermove=e=>{if(drag)move(drag.left+e.clientX-drag.x,drag.top+e.clientY-drag.y);};handle.onpointerup=handle.onpointercancel=()=>{drag=undefined;};
 handle.onkeydown=e=>{const delta:Record<string,number[]>={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(delta[e.key]){e.preventDefault();const r=panel.getBoundingClientRect();move(r.left+delta[e.key][0],r.top+delta[e.key][1]);}};
 panel.onkeydown=e=>{if(e.key==='Escape')clear();};window.addEventListener('resize',clamp);window.addEventListener('scroll',clamp,{passive:true});window.visualViewport?.addEventListener('resize',clamp);window.visualViewport?.addEventListener('scroll',clamp);map.on('resize',clamp);
 const empty=()=>({type:'FeatureCollection',features:[]});
 function setup(){if(!map.getSource(SOURCE))map.addSource(SOURCE,{type:'geojson',data:empty()});if(!map.getLayer(HALO))map.addLayer({id:HALO,type:'line',source:SOURCE,paint:{'line-color':'#172c3f','line-width':7,'line-opacity':.7}});if(!map.getLayer(LINE))map.addLayer({id:LINE,type:'line',source:SOURCE,paint:{'line-color':'#f2c779','line-width':4,'line-opacity':1}});}
 function clear(){selected=undefined;choices=[];page=0;drag=undefined;panel.hidden=true;body.replaceChildren();map.getSource(SOURCE)?.setData(empty());}
 function draw(){body.replaceChildren();panel.hidden=false;
  if(choices.length>1){const label=document.createElement('p');label.textContent=c.choose;body.append(label);const pages=Math.ceil(choices.length/20);page=Math.min(page,pages-1);const pager=document.createElement('div');pager.className='transit-route-pager';const counter=document.createElement('span');counter.textContent=choices.length+' '+c.total+' · '+c.page+' '+(page+1)+'/'+pages;pager.append(counter);if(pages>1){for(const [label,offset]of [[c.previous,-1],[c.next,1]] as const){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=page+offset<0||page+offset>=pages;b.className='transit-route-page-button';b.onclick=()=>{page+=offset;draw();};pager.append(b);}}body.append(pager);for(const r of choices.slice(page*20,page*20+20)){const b=document.createElement('button');b.type='button';b.textContent=[r.values.ref,r.values.name].filter(Boolean).join(' · ')||publicTransitRecordId(r.routeId)||c.missing;b.setAttribute('aria-pressed',String(r.key===selected?.key));b.className='transit-route-choice';b.onclick=()=>select(r);body.append(b);}}
  if(selected){const dl=document.createElement('dl');dl.className='transit-route-fields';for(const [name,val]of [...(publicTransitRecordId(selected.routeId)?[[c.route,publicTransitRecordId(selected.routeId)] as const]:[]),[c.ref,selected.values.ref],[c.name,selected.values.name],[c.from,selected.values.from],[c.to,selected.values.to],[c.operator,selected.values.operator],[c.date,selected.values.source_snapshot],[c.source,selected.values.source]] as const){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=val??c.missing;dd.style.margin='0';dl.append(dt,dd);}body.append(dl);for(const [url,label]of [[selected.sourceURL,c.source],[selected.relationURL,c.relation]] as const){if(url){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.className='transit-route-source';body.append(a);}}if(selected.metadataReference){const p=document.createElement('p');p.textContent=c.metadata;body.append(p);}}
  for(const text of [c.portion,c.noPolice]){const p=document.createElement('p');p.textContent=text;body.append(p);}
  clamp();
 }
 function select(r:RouteChoice){const fresh=transitChoices(options.loaded(),[{properties:{mode:r.mode,route_id:r.routeId}}],options.manifest())[0];if(!fresh){clear();return;}selected=fresh;setup();map.getSource(SOURCE).setData({type:'FeatureCollection',features:fresh.features});draw();}
 return {inspect(point:TransitPoint):boolean{if(destroyed||!map.queryRenderedFeatures||!Number.isFinite(point.x)||!Number.isFinite(point.y))return false;const layers=['metro','tram','bus','extra'].map(g=>'public-transit-'+g+'-lines').filter(id=>map.getLayer(id));if(!layers.length){clear();return false;}let hits;try{hits=map.queryRenderedFeatures([[point.x-6,point.y-6],[point.x+6,point.y+6]],{layers});}catch{clear();return false;}choices=transitChoices(options.loaded(),hits,options.manifest());page=0;if(!choices.length){clear();return false;}select(choices[0]);return true;},clear,update(){if(!selected)return;const hit=[{properties:{mode:selected.mode,route_id:selected.routeId}}],fresh=transitChoices(options.loaded(),hit,options.manifest())[0];if(!fresh){clear();return;}selected=fresh;choices=transitChoices(options.loaded(),choices.map(r=>({properties:{mode:r.mode,route_id:r.routeId}})),options.manifest());setup();map.getSource(SOURCE).setData({type:'FeatureCollection',features:fresh.features});draw();},destroy(){if(destroyed)return;clear();destroyed=true;window.removeEventListener('resize',clamp);window.removeEventListener('scroll',clamp);window.visualViewport?.removeEventListener('resize',clamp);window.visualViewport?.removeEventListener('scroll',clamp);map.off('resize',clamp);panel.remove();for(const id of [LINE,HALO])if(map.getLayer(id))map.removeLayer(id);if(map.getSource(SOURCE))map.removeSource(SOURCE);},get selection(){return selected;},get choiceCount(){return choices.length;}};
}
