export type UFLocale = "de" | "en" | "zh";
export const UF_COPY = {
  "en": {
    "unknown.title": "Reports without a precise location",
    "unknown.intro": "These announcements remain available with their source links. A shown road or outline helps you find the area mentioned; it does not locate the incident. No point is invented to fill the gap.",
    "unknown.filter": "Location detail",
    "unknown.all": "All location types",
    "unknown.district": "District or city only",
    "unknown.street": "Street or route only",
    "unknown.area": "Area only",
    "unknown.venue_reference": "Named place shown for reference",
    "unknown.no_location": "Location not stated or not confirmed",
    "unknown.stats": "{announcements} announcements · {scenes} locations in the selected month and category",
    "unknown.counts": "These totals describe announcements with imprecise locations. One announcement may appear in more than one group. The totals do not establish exact incident locations or measure safety.",
    "unknown.empty": "No reports in this group for the selected month and category.",
    "unknown.originalTime": "Time stated in the source: {time}",
    "unknown.timeUnknown": "No event time is provided in this location summary.",
    "unknown.published": "Publication month: {month}. This is not the event date.",
    "unknown.monthUnknown": "Publication month unavailable.",
    "unknown.source": "Read the source",
    "unknown.sourceUnavailable": "Source link unavailable",
    "unknown.reference": "The map shows a road or outline as a reference range. The actual event position remains unknown.",
    "unknown.noReference": "No area mentioned in this announcement can be shown on the map.",
    "unknown.show": "Read this announcement",
    "unknown.previous": "Previous",
    "unknown.next": "Next",
    "unknown.page": "Page {page} of {pages}",
    "unknown.role.incident": "Incident location",
    "unknown.role.accident": "Accident location",
    "unknown.role.discovery": "Discovery location",
    "unknown.role.operation": "Police operation",
    "unknown.role.arrest": "Arrest location",
    "unknown.role.search": "Search location",
    "unknown.role.background": "Background reference",
    "unknown.role.unknown": "The place’s role is unclear",
    "unknown.summaryDate": "Event date in the report summary: {date}."
  },
  "de": {
    "unknown.title": "Meldungen ohne genaue Ortsangabe",
    "unknown.intro": "Diese Meldungen bleiben mit ihren Quellenlinks erhalten. Genannte Straßen und Umrisse helfen bei der Orientierung, zeigen aber keinen genauen Ereignisort. Eine Position wird nicht erfunden.",
    "unknown.filter": "Ortsangabe",
    "unknown.all": "Alle Ortsangaben",
    "unknown.district": "Nur Bezirk oder Stadt",
    "unknown.street": "Nur Straße oder Strecke",
    "unknown.area": "Nur Gebiet",
    "unknown.venue_reference": "Nur Bezug auf einen benannten Ort",
    "unknown.no_location": "Ort nicht genannt oder nicht bestimmbar",
    "unknown.stats": "{announcements} Meldungen · {scenes} Orte im gewählten Monat und in der gewählten Kategorie",
    "unknown.counts": "Gezählt werden Meldungen mit ungenauen Ortsangaben. Eine Meldung kann in mehreren Gruppen erscheinen. Die Zahlen bestimmen keine genauen Ereignisorte und bewerten keine Sicherheit.",
    "unknown.empty": "Für diesen Monat und diese Kategorie gibt es in dieser Gruppe keine Meldungen.",
    "unknown.originalTime": "Zeitangabe aus der Quelle: {time}",
    "unknown.timeUnknown": "Für diesen Ort enthält die Übersicht keine Ereigniszeit.",
    "unknown.published": "Veröffentlichungsmonat: {month}. Das ist nicht das Ereignisdatum.",
    "unknown.monthUnknown": "Veröffentlichungsmonat nicht verfügbar.",
    "unknown.source": "Quelle lesen",
    "unknown.sourceUnavailable": "Quellenlink nicht verfügbar",
    "unknown.reference": "Die Karte zeigt eine Straße oder einen Umriss zur Orientierung. Der tatsächliche Ereignisort bleibt unbekannt.",
    "unknown.noReference": "Kein in dieser Meldung genannter Bereich lässt sich auf der Karte anzeigen.",
    "unknown.show": "Diese Meldung lesen",
    "unknown.previous": "Zurück",
    "unknown.next": "Weiter",
    "unknown.page": "Seite {page} von {pages}",
    "unknown.role.incident": "Ereignisort",
    "unknown.role.accident": "Unfallort",
    "unknown.role.discovery": "Fundort",
    "unknown.role.operation": "Polizeilicher Einsatz",
    "unknown.role.arrest": "Festnahmeort",
    "unknown.role.search": "Durchsuchungsort",
    "unknown.role.background": "Hintergrundbezug",
    "unknown.role.unknown": "Rolle des Ortes unklar",
    "unknown.summaryDate": "Datum des Ereignisses in der Meldungsübersicht: {date}."
  },
  "zh": {
    "unknown.title": "具体地点无法确定的公告",
    "unknown.intro": "这些公告保留原文链接。道路和轮廓帮助识别提到的范围，不表示实际事件位置；地图不会补画中心点。",
    "unknown.filter": "地点信息",
    "unknown.all": "全部地点类型",
    "unknown.district": "仅行政区或城市",
    "unknown.street": "仅街道或路线",
    "unknown.area": "仅区域",
    "unknown.venue_reference": "场所仅作参照",
    "unknown.no_location": "未给位置或无法确定",
    "unknown.stats": "当前月份与类别：{announcements}篇公告 · {scenes}个地点",
    "unknown.counts": "这里统计含不精确地点的公告，同一篇可能出现在多个分组中。数量不能当作精确事件地点数或安全评分。",
    "unknown.empty": "当前月份与类别下，这一组没有公告。",
    "unknown.originalTime": "原文所述时间：{time}",
    "unknown.timeUnknown": "此地点摘要未提供事件时间。",
    "unknown.published": "公布月份：{month}，不代表事件发生日期。",
    "unknown.monthUnknown": "公布月份未提供。",
    "unknown.source": "阅读原文",
    "unknown.sourceUnavailable": "原文链接未提供",
    "unknown.reference": "地图中的道路或轮廓仅作范围参照，实际事件位置仍未知。",
    "unknown.noReference": "没有可展示的参照范围。",
    "unknown.show": "查看这篇公告",
    "unknown.previous": "上一页",
    "unknown.next": "下一页",
    "unknown.page": "第{page}页，共{pages}页",
    "unknown.role.incident": "案发地点",
    "unknown.role.accident": "事故地点",
    "unknown.role.discovery": "发现地点",
    "unknown.role.operation": "警方行动地点",
    "unknown.role.arrest": "抓捕地点",
    "unknown.role.search": "搜查地点",
    "unknown.role.background": "背景参照地点",
    "unknown.role.unknown": "地点用途未知",
    "unknown.summaryDate": "公告摘要中的事件日期：{date}。"
  }
} as const;
export type UFKey = keyof typeof UF_COPY.en;
export function uncertaintyRoleKey(role: string): UFKey {
  const key = `unknown.role.${role}`;
  return Object.hasOwn(UF_COPY.en, key) ? key as UFKey : "unknown.role.unknown";
}
export function ufText(locale: UFLocale, key: UFKey, params: Record<string, string | number> = {}): string {
  return UF_COPY[locale][key].replace(/\{(\w+)\}/g, (match, name) => String(params[name] ?? match));
}
