export type UFLocale = "de" | "en" | "zh";
export const UF_COPY = {
  "en": {
    "unknown.title": "Reports without a precise location",
    "unknown.intro": "These announcements remain available with their source links. A shown road or outline helps you find the area mentioned; it does not locate the incident. No point is invented to fill the gap.",
    "unknown.filter": "Location detail",
    "unknown.all": "All location types",
    "unknown.district": "District or city only",
    "unknown.street": "Street or route only",
    "unknown.area": "Area only",
    "unknown.venue_reference": "Named place shown for reference",
    "unknown.no_location": "Location not stated or not confirmed",
    "unknown.stats": "{announcements} announcements · {scenes} locations in the selected month and category",
    "unknown.counts": "These totals describe announcements with imprecise locations. One announcement may appear in more than one group. The totals do not establish exact incident locations or measure safety.",
    "unknown.empty": "No reports in this group for the selected month and category.",
    "unknown.originalTime": "Time stated in the source: {time}",
    "unknown.timeUnknown": "No event time is provided in this location summary.",
    "unknown.published": "Publication month: {month}. This is not the event date.",
    "unknown.monthUnknown": "Publication month unavailable.",
    "unknown.source": "Read the source",
    "unknown.sourceUnavailable": "Source link unavailable",
    "unknown.reference": "The map shows a road or outline as a reference range. The actual event position remains unknown.",
    "unknown.noReference": "No area mentioned in this announcement can be shown on the map.",
    "unknown.show": "Read this announcement",
    "unknown.previous": "Previous",
    "unknown.next": "Next",
    "unknown.page": "Page {page} of {pages}",
    "unknown.role.incident": "Incident location",
    "unknown.role.accident": "Accident location",
    "unknown.role.discovery": "Discovery location",
    "unknown.role.operation": "Police operation",
    "unknown.role.arrest": "Arrest location",
    "unknown.role.search": "Search location",
    "unknown.role.background": "Background reference",
    "unknown.role.unknown": "The place’s role is unclear",
    "feedback.title": "Private feedback",
    "feedback.disabled": "Private feedback is not connected yet. Sending is unavailable.",
    "feedback.policy": "Your message goes to the site operator and is not published. No name, email or account is required. Do not include victim identities, exact private addresses or allegations against individuals. This is not an emergency or police reporting service.",
    "feedback.processing": "Cloudflare handles the connection and checks for automated abuse. CrimeMaps does not save your IP address or a browser identifier. It briefly keeps a code derived from the connection address to limit repeated messages, so the service cannot promise full anonymity. Messages cannot be read after 30 days and are removed by the following daily cleanup. Cloudflare’s backups may keep deleted messages for up to seven more days on the Free plan.",
    "feedback.kind": "Feedback type",
    "feedback.correction": "Map or source correction",
    "feedback.accessibility": "Accessibility or usability",
    "feedback.privacy": "Privacy or removal request",
    "feedback.other": "Other feedback",
    "feedback.sourceId": "Announcement ID (optional)",
    "feedback.message": "Message (10–2,000 characters)",
    "feedback.consent": "I have read the private feedback policy and will avoid personal details.",
    "feedback.challenge": "Start the browser check",
    "feedback.challengeNotice": "This loads Cloudflare Turnstile. Cloudflare receives connection and browser details for its checks, and may use them to improve abuse detection. Send only after the check succeeds.",
    "feedback.send": "Send privately",
    "feedback.sending": "Sending…",
    "feedback.success": "Your message was received privately. Keep the receipt number and secret deletion code. The code is shown only on this screen.",
    "feedback.receipt": "Receipt: {id} · expires: {expires}",
    "feedback.token": "Secret deletion code (keep it private)",
    "feedback.delete": "Delete this feedback",
    "feedback.deleted": "The deletion request was processed. To protect privacy, this response is also shown when the message is already deleted or cannot be found.",
    "feedback.deleteTitle": "Delete earlier feedback",
    "feedback.receiptId": "Receipt number",
    "feedback.error": "The message was not confirmed as received. Check the connection or try later.",
    "feedback.rate": "The feedback limit has been reached. Try later.",
    "feedback.validation": "Choose a feedback type, enter 10–2,000 characters and read the policy.",
    "feedback.challengeFailed": "The browser check failed or expired. Run it again.",
    "feedback.retention": "Only authorised site operators can read messages. Visitor comments are not published. You can delete a message with its receipt number and secret deletion code. No reply address is collected.",
    "feedback.clear": "Clear receipt from this screen",
    "feedback.details": "How your message is handled",
    "feedback.policyLink": "Full privacy notice",
    "unknown.summaryDate": "Event date in the report summary: {date}."
  },
  "de": {
    "unknown.title": "Meldungen ohne genaue Ortsangabe",
    "unknown.intro": "Diese Meldungen bleiben mit ihren Quellenlinks erhalten. Genannte Straßen und Umrisse helfen bei der Orientierung, zeigen aber keinen genauen Ereignisort. Eine Position wird nicht erfunden.",
    "unknown.filter": "Ortsangabe",
    "unknown.all": "Alle Ortsangaben",
    "unknown.district": "Nur Bezirk oder Stadt",
    "unknown.street": "Nur Straße oder Strecke",
    "unknown.area": "Nur Gebiet",
    "unknown.venue_reference": "Nur Bezug auf einen benannten Ort",
    "unknown.no_location": "Ort nicht genannt oder nicht bestimmbar",
    "unknown.stats": "{announcements} Meldungen · {scenes} Orte im gewählten Monat und in der gewählten Kategorie",
    "unknown.counts": "Gezählt werden Meldungen mit ungenauen Ortsangaben. Eine Meldung kann in mehreren Gruppen erscheinen. Die Zahlen bestimmen keine genauen Ereignisorte und bewerten keine Sicherheit.",
    "unknown.empty": "Für diesen Monat und diese Kategorie gibt es in dieser Gruppe keine Meldungen.",
    "unknown.originalTime": "Zeitangabe aus der Quelle: {time}",
    "unknown.timeUnknown": "Für diesen Ort enthält die Übersicht keine Ereigniszeit.",
    "unknown.published": "Veröffentlichungsmonat: {month}. Das ist nicht das Ereignisdatum.",
    "unknown.monthUnknown": "Veröffentlichungsmonat nicht verfügbar.",
    "unknown.source": "Quelle lesen",
    "unknown.sourceUnavailable": "Quellenlink nicht verfügbar",
    "unknown.reference": "Die Karte zeigt eine Straße oder einen Umriss zur Orientierung. Der tatsächliche Ereignisort bleibt unbekannt.",
    "unknown.noReference": "Kein in dieser Meldung genannter Bereich lässt sich auf der Karte anzeigen.",
    "unknown.show": "Diese Meldung lesen",
    "unknown.previous": "Zurück",
    "unknown.next": "Weiter",
    "unknown.page": "Seite {page} von {pages}",
    "unknown.role.incident": "Ereignisort",
    "unknown.role.accident": "Unfallort",
    "unknown.role.discovery": "Fundort",
    "unknown.role.operation": "Polizeilicher Einsatz",
    "unknown.role.arrest": "Festnahmeort",
    "unknown.role.search": "Durchsuchungsort",
    "unknown.role.background": "Hintergrundbezug",
    "unknown.role.unknown": "Rolle des Ortes unklar",
    "feedback.title": "Privater Hinweis",
    "feedback.disabled": "Private Hinweise können noch nicht gesendet werden.",
    "feedback.policy": "Ihre Nachricht geht an den Websitebetreiber und wird nicht veröffentlicht. Name, E-Mail-Adresse und Konto sind nicht erforderlich. Nennen Sie keine Namen betroffener Personen, genauen Privatadressen oder Vorwürfe gegen Einzelpersonen. Dies ist kein Notruf und keine polizeiliche Meldestelle.",
    "feedback.processing": "Cloudflare verarbeitet die Verbindung und prüft auf automatisierten Missbrauch. CrimeMaps speichert weder Ihre IP-Adresse noch eine Browserkennung. Um wiederholte Nachrichten zu begrenzen, wird kurzzeitig ein aus der Verbindungsadresse abgeleiteter Code gespeichert. Deshalb kann der Dienst keine vollständige Anonymität zusagen. Nachrichten sind nach 30 Tagen nicht mehr abrufbar und werden bei der nächsten Anfrage oder täglichen Bereinigung entfernt. In Cloudflares Sicherungskopien können gelöschte Nachrichten im kostenlosen Tarif bis zu sieben weitere Tage enthalten sein.",
    "feedback.kind": "Art des Hinweises",
    "feedback.correction": "Korrektur an Karte oder Quelle",
    "feedback.accessibility": "Barrierefreiheit oder Bedienung",
    "feedback.privacy": "Datenschutz oder Entfernung",
    "feedback.other": "Sonstiger Hinweis",
    "feedback.sourceId": "Nummer der Meldung (optional)",
    "feedback.message": "Nachricht (10–2.000 Zeichen)",
    "feedback.consent": "Ich habe die Hinweise zum privaten Formular gelesen und vermeide persönliche Angaben.",
    "feedback.challenge": "Browserprüfung starten",
    "feedback.challengeNotice": "Dabei wird Cloudflare Turnstile geladen. Cloudflare erhält Verbindungs- und Browserdaten für die Prüfung und kann sie zur Verbesserung der Missbrauchserkennung verwenden. Senden ist erst nach erfolgreicher Prüfung möglich.",
    "feedback.send": "Privat senden",
    "feedback.sending": "Wird gesendet…",
    "feedback.success": "Ihre Nachricht ist privat eingegangen. Bewahren Sie die Bestätigungsnummer und den geheimen Löschcode auf. Der Code wird nur auf diesem Bildschirm angezeigt.",
    "feedback.receipt": "Bestätigung: {id} · gültig bis: {expires}",
    "feedback.token": "Geheimer Löschcode (vertraulich aufbewahren)",
    "feedback.delete": "Diesen Hinweis löschen",
    "feedback.deleted": "Die Löschanfrage wurde bearbeitet. Zum Schutz der Privatsphäre erscheint diese Antwort auch, wenn die Nachricht bereits gelöscht oder nicht auffindbar ist.",
    "feedback.deleteTitle": "Früheren Hinweis löschen",
    "feedback.receiptId": "Bestätigungsnummer",
    "feedback.error": "Der Eingang wurde nicht bestätigt. Prüfen Sie die Verbindung oder versuchen Sie es später erneut.",
    "feedback.rate": "Die zulässige Anzahl an Hinweisen ist erreicht. Bitte später erneut versuchen.",
    "feedback.validation": "Wählen Sie eine Art, schreiben Sie 10–2.000 Zeichen und lesen Sie die Hinweise.",
    "feedback.challengeFailed": "Die Browserprüfung ist fehlgeschlagen oder abgelaufen. Bitte erneut starten.",
    "feedback.retention": "Nur befugte Websitebetreiber können die Nachrichten lesen. Besucherkommentare werden nicht veröffentlicht. Mit Bestätigungsnummer und geheimem Löschcode können Sie Ihre Nachricht löschen. Eine Antwortadresse wird nicht erfasst.",
    "feedback.clear": "Bestätigung vom Bildschirm entfernen",
    "feedback.details": "Umgang mit Ihrer Nachricht",
    "feedback.policyLink": "Datenschutzhinweise",
    "unknown.summaryDate": "Datum des Ereignisses in der Meldungsübersicht: {date}."
  },
  "zh": {
    "unknown.title": "具体地点无法确定的公告",
    "unknown.intro": "这些公告保留原文链接。道路和轮廓帮助识别提到的范围，不表示实际事件位置；地图不会补画中心点。",
    "unknown.filter": "地点信息",
    "unknown.all": "全部地点类型",
    "unknown.district": "仅行政区或城市",
    "unknown.street": "仅街道或路线",
    "unknown.area": "仅区域",
    "unknown.venue_reference": "场所仅作参照",
    "unknown.no_location": "未给位置或无法确定",
    "unknown.stats": "当前月份与类别：{announcements}篇公告 · {scenes}个地点",
    "unknown.counts": "这里统计含不精确地点的公告，同一篇可能出现在多个分组中。数量不能当作精确事件地点数或安全评分。",
    "unknown.empty": "当前月份与类别下，这一组没有公告。",
    "unknown.originalTime": "原文所述时间：{time}",
    "unknown.timeUnknown": "此地点摘要未提供事件时间。",
    "unknown.published": "公布月份：{month}，不代表事件发生日期。",
    "unknown.monthUnknown": "公布月份未提供。",
    "unknown.source": "阅读原文",
    "unknown.sourceUnavailable": "原文链接未提供",
    "unknown.reference": "地图中的道路或轮廓仅作范围参照，实际事件位置仍未知。",
    "unknown.noReference": "没有可展示的参照范围。",
    "unknown.show": "查看这篇公告",
    "unknown.previous": "上一页",
    "unknown.next": "下一页",
    "unknown.page": "第{page}页，共{pages}页",
    "unknown.role.incident": "案发地点",
    "unknown.role.accident": "事故地点",
    "unknown.role.discovery": "发现地点",
    "unknown.role.operation": "警方行动地点",
    "unknown.role.arrest": "抓捕地点",
    "unknown.role.search": "搜查地点",
    "unknown.role.background": "背景参照地点",
    "unknown.role.unknown": "地点用途未知",
    "feedback.title": "私密反馈",
    "feedback.disabled": "私密反馈尚未接入，暂时无法发送。",
    "feedback.policy": "消息只交给网站运营者，不会公开。不要求姓名、邮箱或账号。请勿填写受害者身份、私人精确地址或对个人的指控。这里不接收报警或紧急求助。",
    "feedback.processing": "Cloudflare会处理网络连接并检查自动化滥用。CrimeMaps不保存原始IP地址或浏览器标识，会短期保留根据连接地址生成的临时编号，以限制重复发送，不能保证完全匿名。消息在30天后无法读取，并在后续请求或每日清理时删除；免费方案的服务商备份可能再保留最多7天。",
    "feedback.kind": "反馈类型",
    "feedback.correction": "地图或来源纠错",
    "feedback.accessibility": "无障碍或使用问题",
    "feedback.privacy": "隐私或移除请求",
    "feedback.other": "其他反馈",
    "feedback.sourceId": "公告编号（可不填）",
    "feedback.message": "消息（10至2,000个字符）",
    "feedback.consent": "我已阅读私密反馈说明，会避免填写个人信息。",
    "feedback.challenge": "开始浏览器检查",
    "feedback.challengeNotice": "这会加载 Cloudflare Turnstile。Cloudflare 会接收连接和浏览器信息，用于验证，并可能用于改进滥用检测。通过验证后才能发送。",
    "feedback.send": "私密发送",
    "feedback.sending": "正在发送…",
    "feedback.success": "消息已私密接收。请保管回执编号和删除码，删除码只在此屏幕显示。",
    "feedback.receipt": "回执：{id} · 到期时间：{expires}",
    "feedback.token": "删除码（请勿公开）",
    "feedback.delete": "删除这条反馈",
    "feedback.deleted": "删除请求已处理。为保护隐私，记录已删除或不存在时也会显示这条回复。",
    "feedback.deleteTitle": "删除之前的反馈",
    "feedback.receiptId": "回执编号",
    "feedback.error": "尚未确认接收成功，请检查网络或稍后重试。",
    "feedback.rate": "反馈次数已达限制，请稍后重试。",
    "feedback.validation": "请选择反馈类型，填写10至2,000个字符并阅读反馈说明。",
    "feedback.challengeFailed": "浏览器检查失败或已过期，请重新检查。",
    "feedback.retention": "只有获授权的网站运营者可以阅读消息，游客评论不会公开。凭回执编号和删除码可删除消息；系统不收集回复地址。",
    "feedback.clear": "清除屏幕上的回执",
    "feedback.details": "消息如何处理",
    "feedback.policyLink": "完整隐私说明",
    "unknown.summaryDate": "公告摘要中的事件日期：{date}。"
  }
} as const;
export type UFKey = keyof typeof UF_COPY.en;
export function ufText(locale: UFLocale, key: UFKey, params: Record<string, string | number> = {}): string {
  return UF_COPY[locale][key].replace(/\{(\w+)\}/g, (match, name) => String(params[name] ?? match));
}
