import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
const b=await build({entryPoints:[new URL('../src/safety/selection-inspector.ts',import.meta.url).pathname],bundle:true,platform:'node',format:'esm',write:false,loader:{'.css':'empty'}});
const {installSelectionInspector}=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
class Element{
 constructor(tag){this.tag=tag;this.children=[];this.style={};this.hidden=false;this.attributes={};}
 get childNodes(){return this.children;}get isConnected(){return !!this.parentElement||this.tag==='body';}
 append(...items){for(const x of items){x.remove();this.children.push(x);x.parentElement=this;}}
 insertBefore(x,b){x.remove();const i=this.children.indexOf(b);assert(i>=0);this.children.splice(i,0,x);x.parentElement=this;}
 remove(){if(this.parentElement){const a=this.parentElement.children;a.splice(a.indexOf(this),1);this.parentElement=null;}}
 replaceChildren(...x){for(const q of [...this.children])q.remove();this.append(...x);}
 setAttribute(k,v){this.attributes[k]=v;}focus(o){this.focusOptions=o;}click(){this.onclick?.();}closest(){return this.tag==='button'?this:null;}setPointerCapture(){}
 get offsetWidth(){return parseFloat(this.style.width)||280;}get offsetHeight(){return Math.min(220,parseFloat(this.style.maxHeight)||220);}
 getBoundingClientRect(){const l=parseFloat(this.style.left)||0,t=parseFloat(this.style.top)||0;return{left:l,top:t,right:l+this.offsetWidth,bottom:t+this.offsetHeight,width:this.offsetWidth,height:this.offsetHeight};}
}
function fixture(t,width,height){const keys=['window','document','innerWidth','innerHeight'];const old=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));const events=new Map(),ve=new Map();const viewport={offsetLeft:0,offsetTop:0,width,height,addEventListener:(k,f)=>ve.set(k,f),removeEventListener:k=>ve.delete(k)};const body=new Element('body'),home=new Element('aside'),target=new Element('div'),button=new Element('button'),host=new Element('map');host.getBoundingClientRect=()=>({left:0,top:150,right:width,bottom:height});body.append(home);home.append(target);target.append(button);target.id='selection';let clicks=0;button.onclick=()=>clicks++;
Object.assign(globalThis,{window:{visualViewport:viewport,addEventListener:(k,f)=>events.set(k,f),removeEventListener:k=>events.delete(k)},document:{documentElement:new Element('html'),body,createElement:tag=>new Element(tag)},innerWidth:width,innerHeight:height});const inspector=installSelectionInspector(target,host,'en');t.after(()=>{inspector.destroy();for(const[k,d]of old){if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}});return{body,home,target,button,host,inspector,viewport,ve,events,get clicks(){return clicks;}};}
for(const[width,height]of[[375,740],[985,1003],[1280,1000]])test(width+'px: successful selection exposes the original live information node in a compact viewport-bound card',t=>{const f=fixture(t,width,height);assert.equal(f.inspector.visible,false);assert(f.inspector.open());assert(f.inspector.visible);const panel=f.body.children.find(x=>x.className==='geography-panel selection-inspector');assert.equal(panel.children[1].children[0],f.target);assert.equal(f.target.children[0],f.button);f.button.click();assert.equal(f.clicks,1);assert.equal(f.home.children.includes(f.target),false);const r=panel.getBoundingClientRect();assert(r.left>=12&&r.right<=width-12&&r.top>=162&&r.bottom<=height-12);panel.children[0].children[1].click();assert.equal(f.inspector.visible,false);assert.equal(f.target.parentElement,f.home);f.button.click();assert.equal(f.clicks,2);});
test('selected content keeps listeners through refresh, close and reopening without cloning or duplicate IDs',t=>{const f=fixture(t,985,1003);f.inspector.open();const next=new Element('button');let n=0;next.onclick=()=>n++;f.target.replaceChildren(next);assert(f.inspector.visible);next.click();assert.equal(n,1);f.inspector.close();assert.equal(f.target.parentElement,f.home);assert(f.inspector.open());next.click();assert.equal(n,2);const visit=e=>[e,...e.children.flatMap(visit)];assert.equal(visit(f.body).filter(x=>x.id==='selection').length,1);});
test('close/month-source reset restores unique information DOM; ordinary content changes cannot open an inactive inspector',t=>{const f=fixture(t,375,740);f.inspector.open();f.inspector.close();f.target.replaceChildren(new Element('p'));assert.equal(f.inspector.visible,false);f.target.replaceChildren();assert.equal(f.inspector.open(),false);assert.equal(f.target.parentElement,f.home);f.inspector.destroy();assert.equal(f.events.size,0);assert.equal(f.ve.size,0);});
test('drag and visual viewport resize clamp the same selected DOM rather than clearing it',t=>{const f=fixture(t,985,1003);f.inspector.open();const panel=f.body.children.find(x=>x.className==='geography-panel selection-inspector'),handle=panel.children[0];handle.onpointerdown({target:handle,clientX:500,clientY:300,pointerId:1});handle.onpointermove({clientX:5000,clientY:5000});let r=panel.getBoundingClientRect();assert(r.right<=973&&r.bottom<=991);f.viewport.width=320;f.viewport.height=740;f.ve.get('resize')();r=panel.getBoundingClientRect();assert(r.left>=12&&r.right<=308&&r.bottom<=728);assert(f.inspector.visible);assert.equal(panel.children[1].children[0],f.target);});
test('real main caller opens only deliberate POI/scene/hex/OSM selections; month and teardown close and preserve transit priority',async()=>{const main=await readFile(new URL('../src/safety/main.ts',import.meta.url),'utf8');assert(main.includes('showSelection();\n          selectionInspector.open();'));assert(main.includes('replaceChildren(panel);selectionInspector.open();'));assert(main.includes('async function loadMonth() {\n  selectionInspector.close();basicOsmPanel=undefined;'));assert(main.includes('selectionInspector.destroy();'));const start=main.indexOf('map.on("click"');assert(main.indexOf('transitIncidentLayers=',start)<main.indexOf('inspectStopAt',start));assert(main.indexOf('inspectStopAt',start)<main.indexOf('transitPriorityLayers=',start));assert(!b.outputFiles[0].text.includes('cloneNode'));});
